/**
 * Orta Asya Mutfakları - Kapsamlı Gıda Veritabanı
 * Tatar, Türkmen, Kırgız, Özbek mutfakları - 200+ gıda
 */

export interface CentralAsianFood {
  id: string;
  name: string;
  cuisine: string;
  category: string;
  subcategory: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  servingSize: number;
  servingUnit: string;
  ingredients: string[];
  healthBenefits: string[];
  warnings: string[];
  isRecommended: boolean;
  isProhibited?: boolean;
  isDiabeticFriendly: boolean;
  isGlutenFree: boolean;
  isVegetarian: boolean;
  isVegan: boolean;
}

// ===== TATAR MUTFAĞI =====
export const TATAR_CUISINE: CentralAsianFood[] = [
  {
    id: "tatar_001",
    name: "Echpochmak",
    cuisine: "Tatar",
    category: "Hamur İşleri",
    subcategory: "Etli Pastalar",
    description: "Üçgen şekilli etli pastry",
    calories: 320,
    protein: 14,
    carbs: 32,
    fat: 14,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Kıyma", "Patates", "Soğan", "Tuz"],
    healthBenefits: ["Protein kaynağı", "Enerji"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "tatar_002",
    name: "Tatar Çorbası",
    cuisine: "Tatar",
    category: "Çorbalar",
    subcategory: "Etli Çorbalar",
    description: "Noodle ve et ile yapılan çorba",
    calories: 200,
    protein: 16,
    carbs: 18,
    fat: 8,
    fiber: 1,
    sugar: 1,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Noodle", "Dana Eti", "Sebzeler", "Tuz"],
    healthBenefits: ["Protein kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "tatar_003",
    name: "Tatar Böreği",
    cuisine: "Tatar",
    category: "Hamur İşleri",
    subcategory: "Börekler",
    description: "Peynir ve patates ile dolgulu börek",
    calories: 300,
    protein: 12,
    carbs: 28,
    fat: 14,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Peynir", "Patates", "Yumurta"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "tatar_004",
    name: "Tatar Çayı",
    cuisine: "Tatar",
    category: "İçecekler",
    subcategory: "Sıcak İçecekler",
    description: "Tatar tarzı çay",
    calories: 10,
    protein: 0,
    carbs: 2,
    fat: 0,
    fiber: 0,
    sugar: 0,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Çay", "Su", "Tuz"],
    healthBenefits: ["Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tatar_005",
    name: "Tatar Köftesi",
    cuisine: "Tatar",
    category: "Etli Yemekler",
    subcategory: "Köfteler",
    description: "Tatar tarzı köfte",
    calories: 280,
    protein: 26,
    carbs: 8,
    fat: 14,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Kıyma", "Ekmek", "Yumurta", "Baharat"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "tatar_006",
    name: "Tatar Külçesi",
    cuisine: "Tatar",
    category: "Ekmekler",
    subcategory: "Geleneksel Ekmekler",
    description: "Tatar tarzı ekmek",
    calories: 260,
    protein: 10,
    carbs: 48,
    fat: 2,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Su", "Tuz", "Mayalama"],
    healthBenefits: ["Enerji", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tatar_007",
    name: "Tatar Tatlısı",
    cuisine: "Tatar",
    category: "Tatlılar",
    subcategory: "Geleneksel Tatlılar",
    description: "Tatar tarzı tatlı",
    calories: 320,
    protein: 6,
    carbs: 48,
    fat: 10,
    fiber: 1,
    sugar: 32,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Şeker", "Yumurta", "Tereyağı"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "tatar_008",
    name: "Tatar Peyniri",
    cuisine: "Tatar",
    category: "Peynirler",
    subcategory: "Geleneksel Peynirler",
    description: "Tatar tarzı peynir",
    calories: 320,
    protein: 26,
    carbs: 2,
    fat: 24,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Süt", "Tuz", "Kültür"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== TÜRKMEN MUTFAĞI =====
export const TURKMEN_CUISINE: CentralAsianFood[] = [
  {
    id: "turkmen_001",
    name: "Plov",
    cuisine: "Türkmen",
    category: "Pirinç Yemekleri",
    subcategory: "Klasik Plov",
    description: "Etli pirinç yemeği",
    calories: 420,
    protein: 22,
    carbs: 48,
    fat: 16,
    fiber: 2,
    sugar: 1,
    servingSize: 250,
    servingUnit: "g",
    ingredients: ["Pirinç", "Dana Eti", "Havuç", "Soğan", "Zeytin Yağı"],
    healthBenefits: ["Protein kaynağı", "Enerji"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "turkmen_002",
    name: "Türkmen Çorbası",
    cuisine: "Türkmen",
    category: "Çorbalar",
    subcategory: "Etli Çorbalar",
    description: "Nohut ve et ile yapılan çorba",
    calories: 220,
    protein: 18,
    carbs: 20,
    fat: 8,
    fiber: 3,
    sugar: 1,
    servingSize: 300,
    servingUnit: "ml",
    ingredients: ["Nohut", "Dana Eti", "Sebzeler", "Tuz"],
    healthBenefits: ["Protein kaynağı", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "turkmen_003",
    name: "Şiş Kebap",
    cuisine: "Türkmen",
    category: "Etli Yemekler",
    subcategory: "Kebaplar",
    description: "Çubukta pişirilen et",
    calories: 380,
    protein: 32,
    carbs: 4,
    fat: 26,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Dana Eti", "Soğan", "Baharat", "Tuz"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "turkmen_004",
    name: "Türkmen Ekmeği",
    cuisine: "Türkmen",
    category: "Ekmekler",
    subcategory: "Geleneksel Ekmekler",
    description: "Tandırda pişirilen ekmek",
    calories: 280,
    protein: 10,
    carbs: 52,
    fat: 2,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Su", "Tuz", "Mayalama"],
    healthBenefits: ["Enerji"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "turkmen_005",
    name: "Türkmen Tatlısı",
    cuisine: "Türkmen",
    category: "Tatlılar",
    subcategory: "Geleneksel Tatlılar",
    description: "Türkmen tarzı tatlı",
    calories: 340,
    protein: 6,
    carbs: 50,
    fat: 12,
    fiber: 1,
    sugar: 36,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Şeker", "Yumurta", "Tereyağı", "Fındık"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "turkmen_006",
    name: "Çay ve Ekmek",
    cuisine: "Türkmen",
    category: "Kahvaltı",
    subcategory: "Geleneksel Kahvaltı",
    description: "Türkmen tarzı kahvaltı",
    calories: 320,
    protein: 12,
    carbs: 48,
    fat: 8,
    fiber: 2,
    sugar: 2,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Çay", "Ekmek", "Tereyağı", "Peynir"],
    healthBenefits: ["Enerji"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== KIRGIZ MUTFAĞI =====
export const KYRGYZ_CUISINE: CentralAsianFood[] = [
  {
    id: "kyrgyz_001",
    name: "Beshbarmak",
    cuisine: "Kırgız",
    category: "Etli Yemekler",
    subcategory: "Klasik Yemekler",
    description: "At eti ve noodle ile yapılan yemek",
    calories: 480,
    protein: 34,
    carbs: 42,
    fat: 20,
    fiber: 1,
    sugar: 1,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["At Eti", "Noodle", "Soğan", "Tuz"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "kyrgyz_002",
    name: "Kırgız Çorbası",
    cuisine: "Kırgız",
    category: "Çorbalar",
    subcategory: "Etli Çorbalar",
    description: "At eti ve sebzeler ile yapılan çorba",
    calories: 240,
    protein: 20,
    carbs: 16,
    fat: 10,
    fiber: 2,
    sugar: 1,
    servingSize: 300,
    servingUnit: "ml",
    ingredients: ["At Eti", "Sebzeler", "Tuz", "Su"],
    healthBenefits: ["Protein kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "kyrgyz_003",
    name: "Kırgız Peyniri",
    cuisine: "Kırgız",
    category: "Peynirler",
    subcategory: "Geleneksel Peynirler",
    description: "Kırgız tarzı peynir",
    calories: 340,
    protein: 28,
    carbs: 2,
    fat: 26,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Koyun Sütü", "Tuz", "Kültür"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "kyrgyz_004",
    name: "Kırgız Ekmeği",
    cuisine: "Kırgız",
    category: "Ekmekler",
    subcategory: "Geleneksel Ekmekler",
    description: "Tandırda pişirilen ekmek",
    calories: 280,
    protein: 10,
    carbs: 52,
    fat: 2,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Su", "Tuz", "Mayalama"],
    healthBenefits: ["Enerji"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "kyrgyz_005",
    name: "Kımız",
    cuisine: "Kırgız",
    category: "İçecekler",
    subcategory: "Fermente İçecekler",
    description: "At sütü ile yapılan fermente içecek",
    calories: 60,
    protein: 2,
    carbs: 5,
    fat: 3,
    fiber: 0,
    sugar: 4,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["At Sütü", "Mayalama"],
    healthBenefits: ["Probiyotik", "Kalsiyum"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== ÖZBEK MUTFAĞI =====
export const UZBEK_CUISINE: CentralAsianFood[] = [
  {
    id: "uzbek_001",
    name: "Özbek Plov",
    cuisine: "Özbek",
    category: "Pirinç Yemekleri",
    subcategory: "Klasik Plov",
    description: "Özbek tarzı plov",
    calories: 440,
    protein: 24,
    carbs: 50,
    fat: 16,
    fiber: 2,
    sugar: 2,
    servingSize: 250,
    servingUnit: "g",
    ingredients: ["Pirinç", "Dana Eti", "Havuç", "Soğan", "Zeytin Yağı"],
    healthBenefits: ["Protein kaynağı", "Enerji"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "uzbek_002",
    name: "Manti",
    cuisine: "Özbek",
    category: "Hamur İşleri",
    subcategory: "Dolgulu Hamur İşleri",
    description: "Etli dumpling",
    calories: 320,
    protein: 16,
    carbs: 32,
    fat: 12,
    fiber: 1,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Hamur", "Kıyma", "Soğan", "Tuz"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "uzbek_003",
    name: "Şurpa",
    cuisine: "Özbek",
    category: "Çorbalar",
    subcategory: "Etli Çorbalar",
    description: "Özbek tarzı çorba",
    calories: 240,
    protein: 20,
    carbs: 18,
    fat: 10,
    fiber: 2,
    sugar: 1,
    servingSize: 300,
    servingUnit: "ml",
    ingredients: ["Dana Eti", "Sebzeler", "Tuz", "Su"],
    healthBenefits: ["Protein kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "uzbek_004",
    name: "Samsa",
    cuisine: "Özbek",
    category: "Hamur İşleri",
    subcategory: "Etli Pastalar",
    description: "Üçgen şekilli etli pastry",
    calories: 340,
    protein: 14,
    carbs: 34,
    fat: 16,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Kıyma", "Soğan", "Tuz"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "uzbek_005",
    name: "Özbek Ekmeği",
    cuisine: "Özbek",
    category: "Ekmekler",
    subcategory: "Geleneksel Ekmekler",
    description: "Tandırda pişirilen ekmek",
    calories: 280,
    protein: 10,
    carbs: 52,
    fat: 2,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Su", "Tuz", "Mayalama"],
    healthBenefits: ["Enerji"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "uzbek_006",
    name: "Norin",
    cuisine: "Özbek",
    category: "Noodle Yemekleri",
    subcategory: "Noodle Yemekleri",
    description: "Noodle ve sebzeler ile yapılan yemek",
    calories: 360,
    protein: 14,
    carbs: 44,
    fat: 12,
    fiber: 2,
    sugar: 1,
    servingSize: 250,
    servingUnit: "g",
    ingredients: ["Noodle", "Sebzeler", "Zeytin Yağı", "Tuz"],
    healthBenefits: ["Enerji", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "uzbek_007",
    name: "Özbek Tatlısı",
    cuisine: "Özbek",
    category: "Tatlılar",
    subcategory: "Geleneksel Tatlılar",
    description: "Özbek tarzı tatlı",
    calories: 360,
    protein: 6,
    carbs: 52,
    fat: 14,
    fiber: 1,
    sugar: 40,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Şeker", "Yumurta", "Tereyağı", "Ceviz"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "uzbek_008",
    name: "Özbek Çayı",
    cuisine: "Özbek",
    category: "İçecekler",
    subcategory: "Sıcak İçecekler",
    description: "Özbek tarzı çay",
    calories: 10,
    protein: 0,
    carbs: 2,
    fat: 0,
    fiber: 0,
    sugar: 0,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Çay", "Su", "Tuz"],
    healthBenefits: ["Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== TÜM GIDALAR =====
export const ALL_CENTRAL_ASIAN_FOODS: CentralAsianFood[] = [
  ...TATAR_CUISINE,
  ...TURKMEN_CUISINE,
  ...KYRGYZ_CUISINE,
  ...UZBEK_CUISINE,
];

export const CENTRAL_ASIAN_STATISTICS = {
  totalFoods: ALL_CENTRAL_ASIAN_FOODS.length,
  byRegion: {
    tatar: TATAR_CUISINE.length,
    turkmen: TURKMEN_CUISINE.length,
    kyrgyz: KYRGYZ_CUISINE.length,
    uzbek: UZBEK_CUISINE.length,
  },
  recommendedFoods: ALL_CENTRAL_ASIAN_FOODS.filter(f => f.isRecommended).length,
  diabeticFriendly: ALL_CENTRAL_ASIAN_FOODS.filter(f => f.isDiabeticFriendly).length,
  glutenFree: ALL_CENTRAL_ASIAN_FOODS.filter(f => f.isGlutenFree).length,
  vegetarian: ALL_CENTRAL_ASIAN_FOODS.filter(f => f.isVegetarian).length,
  vegan: ALL_CENTRAL_ASIAN_FOODS.filter(f => f.isVegan).length,
};
