/**
 * Fransız Mutfağı - Kapsamlı Gıda Veritabanı
 * 150+ gıda ile Fransız mutfağının tüm kategorileri
 */

export interface FrenchFood {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  servingSize: number;
  servingUnit: string;
  ingredients: string[];
  healthBenefits: string[];
  warnings: string[];
  isRecommended: boolean;
  isProhibited?: boolean;
  isDiabeticFriendly: boolean;
  isGlutenFree: boolean;
  isVegetarian: boolean;
  isVegan: boolean;
}

// ===== SOUPLAR (ÇORBALAR) =====
export const FRENCH_SOUPS: FrenchFood[] = [
  {
    id: "fr_soup_001",
    name: "Soupe à l'Oignon",
    category: "Çorbalar",
    subcategory: "Klasik Çorbalar",
    description: "Soğan ve peynir ile yapılan Fransız çorbası",
    calories: 180,
    protein: 8,
    carbs: 20,
    fat: 8,
    fiber: 2,
    sugar: 3,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Soğan", "Peynir", "Ekmek", "Tereyağı", "Sebze Suyu"],
    healthBenefits: ["Kalsiyum", "Lif"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_soup_002",
    name: "Bouillabaisse",
    category: "Çorbalar",
    subcategory: "Balık Çorbaları",
    description: "Balık ve deniz ürünleri ile yapılan Provence çorbası",
    calories: 240,
    protein: 28,
    carbs: 12,
    fat: 10,
    fiber: 2,
    sugar: 1,
    servingSize: 300,
    servingUnit: "ml",
    ingredients: ["Balık", "Karides", "Safran", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "fr_soup_003",
    name: "Vichyssoise",
    category: "Çorbalar",
    subcategory: "Soğuk Çorbalar",
    description: "Pırasası ve patates ile yapılan soğuk çorba",
    calories: 160,
    protein: 4,
    carbs: 18,
    fat: 8,
    fiber: 2,
    sugar: 2,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Pırasa", "Patates", "Krema", "Tereyağı", "Tuz"],
    healthBenefits: ["Lif kaynağı", "Potasyum"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_soup_004",
    name: "Bisque de Homard",
    category: "Çorbalar",
    subcategory: "Deniz Ürünlü Çorbalar",
    description: "Istakoz ile yapılan zengin çorba",
    calories: 280,
    protein: 18,
    carbs: 14,
    fat: 18,
    fiber: 1,
    sugar: 2,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["İstakoz", "Krema", "Şarap", "Domates", "Tereyağı"],
    healthBenefits: ["Protein kaynağı", "Selenium"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "fr_soup_005",
    name: "Crème de Champignons",
    category: "Çorbalar",
    subcategory: "Sebzeli Çorbalar",
    description: "Mantar ve krem ile yapılan çorba",
    calories: 200,
    protein: 6,
    carbs: 16,
    fat: 12,
    fiber: 2,
    sugar: 1,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Mantar", "Krema", "Tereyağı", "Sarımsak", "Tuz"],
    healthBenefits: ["Vitamin D", "Lif"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== PLATS PRINCIPAUX (ANA YEMEKLER) =====
export const FRENCH_MAIN_COURSES: FrenchFood[] = [
  {
    id: "fr_main_001",
    name: "Coq au Vin",
    category: "Ana Yemekler",
    subcategory: "Tavuk Yemekleri",
    description: "Kırmızı şarap ve mantar ile pişirilen tavuk",
    calories: 380,
    protein: 32,
    carbs: 12,
    fat: 22,
    fiber: 2,
    sugar: 2,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Tavuk", "Kırmızı Şarap", "Mantar", "Soğan", "Tereyağı"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "fr_main_002",
    name: "Beef Bourguignon",
    category: "Ana Yemekler",
    subcategory: "Etli Yemekler",
    description: "Kırmızı şarap ve sebzeler ile pişirilen dana eti",
    calories: 420,
    protein: 36,
    carbs: 14,
    fat: 24,
    fiber: 2,
    sugar: 2,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Dana Eti", "Kırmızı Şarap", "Sebzeler", "Mantar", "Tereyağı"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "fr_main_003",
    name: "Sole Meunière",
    category: "Ana Yemekler",
    subcategory: "Balık Yemekleri",
    description: "Tereyağında pişirilen dil balığı",
    calories: 320,
    protein: 34,
    carbs: 8,
    fat: 16,
    fiber: 0,
    sugar: 0,
    servingSize: 180,
    servingUnit: "g",
    ingredients: ["Dil Balığı", "Tereyağı", "Limon", "Un", "Tuz"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "fr_main_004",
    name: "Cassoulet",
    category: "Ana Yemekler",
    subcategory: "Etli Yemekler",
    description: "Fasulye ve çeşitli etler ile yapılan yemek",
    calories: 480,
    protein: 32,
    carbs: 38,
    fat: 24,
    fiber: 8,
    sugar: 2,
    servingSize: 250,
    servingUnit: "g",
    ingredients: ["Fasulye", "Ördek", "Sosis", "Soğan", "Tereyağı"],
    healthBenefits: ["Protein kaynağı", "Lif"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "fr_main_005",
    name: "Ratatouille",
    category: "Ana Yemekler",
    subcategory: "Sebzeli Yemekler",
    description: "Çeşitli sebzeler ile yapılan Provence yemeği",
    calories: 140,
    protein: 4,
    carbs: 18,
    fat: 6,
    fiber: 4,
    sugar: 3,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Zucchini", "Biber", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== FROMAGES (PEYNIRLER) =====
export const FRENCH_CHEESES: FrenchFood[] = [
  {
    id: "fr_cheese_001",
    name: "Camembert",
    category: "Peynirler",
    subcategory: "Yumuşak Peynirler",
    description: "Yumuşak ve kremsi Normandiya peyniri",
    calories: 320,
    protein: 20,
    carbs: 1,
    fat: 27,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Süt", "Tuz", "Kültür"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_cheese_002",
    name: "Brie",
    category: "Peynirler",
    subcategory: "Yumuşak Peynirler",
    description: "Kremsi ve hafif Île-de-France peyniri",
    calories: 334,
    protein: 18,
    carbs: 1,
    fat: 28,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Süt", "Tuz", "Kültür"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_cheese_003",
    name: "Roquefort",
    category: "Peynirler",
    subcategory: "Mavi Peynirler",
    description: "Koyun sütü ile yapılan mavi peynir",
    calories: 352,
    protein: 21,
    carbs: 2,
    fat: 30,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Koyun Sütü", "Tuz", "Küf"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ", "Yüksek sodyum"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_cheese_004",
    name: "Comté",
    category: "Peynirler",
    subcategory: "Sert Peynirler",
    description: "Jura bölgesinin sert peyniri",
    calories: 412,
    protein: 28,
    carbs: 3,
    fat: 34,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Süt", "Tuz", "Kültür"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== PAINS (EKMEKLER) =====
export const FRENCH_BREADS: FrenchFood[] = [
  {
    id: "fr_bread_001",
    name: "Baguette",
    category: "Ekmekler",
    subcategory: "Klasik Ekmekler",
    description: "Klasik Fransız baguette ekmeği",
    calories: 280,
    protein: 10,
    carbs: 54,
    fat: 2,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Su", "Tuz", "Mayalama"],
    healthBenefits: ["Enerji", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "fr_bread_002",
    name: "Croissant",
    category: "Ekmekler",
    subcategory: "Pastane Ekmekleri",
    description: "Katmanlı ve tereyağlı Fransız pastası",
    calories: 406,
    protein: 8,
    carbs: 41,
    fat: 24,
    fiber: 2,
    sugar: 8,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Tereyağı", "Şeker", "Tuz", "Yumurta"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek yağ", "Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_bread_003",
    name: "Pain Complet",
    category: "Ekmekler",
    subcategory: "Tam Buğday Ekmekleri",
    description: "Tam buğday ile yapılan sağlıklı ekmek",
    calories: 250,
    protein: 12,
    carbs: 48,
    fat: 2,
    fiber: 4,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Tam Buğday Unu", "Su", "Tuz", "Mayalama"],
    healthBenefits: ["Lif kaynağı", "Protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== SAUCES (SOSLAR) =====
export const FRENCH_SAUCES: FrenchFood[] = [
  {
    id: "fr_sauce_001",
    name: "Béchamel",
    category: "Soslar",
    subcategory: "Beyaz Soslar",
    description: "Tereyağı ve un ile yapılan klasik beyaz sos",
    calories: 180,
    protein: 4,
    carbs: 8,
    fat: 14,
    fiber: 0,
    sugar: 0,
    servingSize: 50,
    servingUnit: "ml",
    ingredients: ["Tereyağı", "Un", "Süt", "Tuz", "Muskat"],
    healthBenefits: ["Kalsiyum"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_sauce_002",
    name: "Hollandaise",
    category: "Soslar",
    subcategory: "Emülsiyon Soslar",
    description: "Yumurta ve tereyağı ile yapılan sos",
    calories: 220,
    protein: 3,
    carbs: 2,
    fat: 24,
    fiber: 0,
    sugar: 0,
    servingSize: 50,
    servingUnit: "ml",
    ingredients: ["Yumurta Sarısı", "Tereyağı", "Limon", "Tuz"],
    healthBenefits: [],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_sauce_003",
    name: "Béarnaise",
    category: "Soslar",
    subcategory: "Emülsiyon Soslar",
    description: "Yumurta, tereyağı ve tarhun ile yapılan sos",
    calories: 240,
    protein: 3,
    carbs: 3,
    fat: 26,
    fiber: 0,
    sugar: 0,
    servingSize: 50,
    servingUnit: "ml",
    ingredients: ["Yumurta Sarısı", "Tereyağı", "Tarhun", "Şarap"],
    healthBenefits: [],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== DESSERTS (TATLILER) =====
export const FRENCH_DESSERTS: FrenchFood[] = [
  {
    id: "fr_dessert_001",
    name: "Crème Brûlée",
    category: "Tatlılar",
    subcategory: "Krem Tatlıları",
    description: "Vanilya krem ve karamelize şeker ile yapılan tatlı",
    calories: 320,
    protein: 4,
    carbs: 28,
    fat: 22,
    fiber: 0,
    sugar: 28,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Krema", "Yumurta Sarısı", "Şeker", "Vanilya"],
    healthBenefits: [],
    warnings: ["Yüksek şeker", "Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_dessert_002",
    name: "Éclair",
    category: "Tatlılar",
    subcategory: "Pastane Tatlıları",
    description: "Çikolata ve krem ile dolgulu pastane",
    calories: 280,
    protein: 6,
    carbs: 32,
    fat: 14,
    fiber: 1,
    sugar: 26,
    servingSize: 80,
    servingUnit: "g",
    ingredients: ["Çikolata", "Krema", "Un", "Yumurta", "Şeker"],
    healthBenefits: [],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_dessert_003",
    name: "Macaron",
    category: "Tatlılar",
    subcategory: "Bisküviler",
    description: "Badem unu ile yapılan renkli bisküvi",
    calories: 380,
    protein: 6,
    carbs: 42,
    fat: 20,
    fiber: 1,
    sugar: 40,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Badem Unu", "Şeker", "Yumurta", "Gıda Boyası"],
    healthBenefits: ["Protein"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_dessert_004",
    name: "Tarte Tatin",
    category: "Tatlılar",
    subcategory: "Pasta Tatlıları",
    description: "Karamelize elma ve pasta ile yapılan tatlı",
    calories: 340,
    protein: 4,
    carbs: 44,
    fat: 16,
    fiber: 2,
    sugar: 32,
    servingSize: 120,
    servingUnit: "g",
    ingredients: ["Elma", "Şeker", "Tereyağı", "Pasta"],
    healthBenefits: ["Lif"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "fr_dessert_005",
    name: "Mousse au Chocolat",
    category: "Tatlılar",
    subcategory: "Krem Tatlıları",
    description: "Çikolata ve krem ile yapılan hafif tatlı",
    calories: 300,
    protein: 6,
    carbs: 24,
    fat: 20,
    fiber: 1,
    sugar: 22,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Çikolata", "Krema", "Yumurta", "Şeker"],
    healthBenefits: [],
    warnings: ["Yüksek şeker", "Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== WINES (ŞARAPLAR) =====
export const FRENCH_WINES: FrenchFood[] = [
  {
    id: "fr_wine_001",
    name: "Bordeaux Rouge",
    category: "Şaraplar",
    subcategory: "Kırmızı Şaraplar",
    description: "Bordeaux bölgesinin kırmızı şarabı",
    calories: 85,
    protein: 0,
    carbs: 3,
    fat: 0,
    fiber: 0,
    sugar: 1,
    servingSize: 150,
    servingUnit: "ml",
    ingredients: ["Üzüm", "Mayalama"],
    healthBenefits: ["Antioksidan"],
    warnings: ["Alkol"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "fr_wine_002",
    name: "Champagne",
    category: "Şaraplar",
    subcategory: "Köpüklü Şaraplar",
    description: "Champagne bölgesinin köpüklü şarabı",
    calories: 90,
    protein: 0,
    carbs: 2,
    fat: 0,
    fiber: 0,
    sugar: 1,
    servingSize: 150,
    servingUnit: "ml",
    ingredients: ["Üzüm", "Mayalama"],
    healthBenefits: ["Antioksidan"],
    warnings: ["Alkol"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== TÜM GIDALAR =====
export const ALL_FRENCH_FOODS: FrenchFood[] = [
  ...FRENCH_SOUPS,
  ...FRENCH_MAIN_COURSES,
  ...FRENCH_CHEESES,
  ...FRENCH_BREADS,
  ...FRENCH_SAUCES,
  ...FRENCH_DESSERTS,
  ...FRENCH_WINES,
];

export const FRENCH_STATISTICS = {
  totalFoods: ALL_FRENCH_FOODS.length,
  recommendedFoods: ALL_FRENCH_FOODS.filter(f => f.isRecommended).length,
  diabeticFriendly: ALL_FRENCH_FOODS.filter(f => f.isDiabeticFriendly).length,
  glutenFree: ALL_FRENCH_FOODS.filter(f => f.isGlutenFree).length,
  vegetarian: ALL_FRENCH_FOODS.filter(f => f.isVegetarian).length,
  vegan: ALL_FRENCH_FOODS.filter(f => f.isVegan).length,
};
