/**
 * İtalyan Mutfağı - Kapsamlı Gıda Veritabanı
 * 150+ gıda ile İtalyan mutfağının tüm kategorileri
 */

export interface ItalianFood {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  servingSize: number;
  servingUnit: string;
  ingredients: string[];
  healthBenefits: string[];
  warnings: string[];
  isRecommended: boolean;
  isProhibited?: boolean;
  isDiabeticFriendly: boolean;
  isGlutenFree: boolean;
  isVegetarian: boolean;
  isVegan: boolean;
}

// ===== PASTALAR =====
export const ITALIAN_PASTA: ItalianFood[] = [
  {
    id: "it_pasta_001",
    name: "Spaghetti Carbonara",
    category: "Pastalar",
    subcategory: "Klasik Pastalar",
    description: "Yumurta, peynir ve pancetta ile yapılan klasik İtalyan pastası",
    calories: 450,
    protein: 18,
    carbs: 45,
    fat: 22,
    fiber: 2,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Spaghetti", "Yumurta", "Pecorino Romano", "Pancetta", "Karabiber"],
    healthBenefits: ["Protein kaynağı", "Enerji"],
    warnings: ["Yüksek yağ", "Yüksek kalori"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pasta_002",
    name: "Penne Arrabbiata",
    category: "Pastalar",
    subcategory: "Domates Soslu Pastalar",
    description: "Acı biber ve domates ile yapılan basit İtalyan pastası",
    calories: 320,
    protein: 12,
    carbs: 48,
    fat: 8,
    fiber: 3,
    sugar: 4,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Penne", "Domates", "Acı Biber", "Sarımsak", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "it_pasta_003",
    name: "Fettuccine Alfredo",
    category: "Pastalar",
    subcategory: "Krem Soslu Pastalar",
    description: "Tereyağı ve parmesan peyniri ile yapılan zengin pasta",
    calories: 520,
    protein: 16,
    carbs: 42,
    fat: 32,
    fiber: 2,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Fettuccine", "Tereyağı", "Parmesan Peyniri", "Krem", "Tuz"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Çok yüksek yağ", "Yüksek kalori"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_pasta_004",
    name: "Lasagna Bolognese",
    category: "Pastalar",
    subcategory: "Fırında Pişmiş Pastalar",
    description: "Kıyma ve béchamel sosu ile yapılan katmanlı pasta",
    calories: 480,
    protein: 28,
    carbs: 38,
    fat: 24,
    fiber: 2,
    sugar: 3,
    servingSize: 250,
    servingUnit: "g",
    ingredients: ["Lasagna Levhası", "Kıyma", "Domates", "Béchamel", "Parmesan"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Yüksek yağ", "Yüksek kalori"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pasta_005",
    name: "Ravioli Ricotta Ispanak",
    category: "Pastalar",
    subcategory: "Dolgulu Pastalar",
    description: "Ricotta peyniri ve ispanak ile dolgulu ravioli",
    calories: 380,
    protein: 14,
    carbs: 40,
    fat: 18,
    fiber: 3,
    sugar: 2,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Ravioli", "Ricotta", "Ispanak", "Parmesan", "Yumurta"],
    healthBenefits: ["Demir", "Kalsiyum", "Lif"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_pasta_006",
    name: "Tortellini Pesto",
    category: "Pastalar",
    subcategory: "Dolgulu Pastalar",
    description: "Pesto sosu ile servis edilen dolgulu tortellini",
    calories: 420,
    protein: 15,
    carbs: 42,
    fat: 20,
    fiber: 2,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Tortellini", "Pesto", "Parmesan", "Fındık", "Sarımsak"],
    healthBenefits: ["Protein", "Sağlıklı yağlar"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_pasta_007",
    name: "Linguine Frutti di Mare",
    category: "Pastalar",
    subcategory: "Deniz Ürünlü Pastalar",
    description: "Deniz ürünleri ile yapılan hafif pasta",
    calories: 380,
    protein: 22,
    carbs: 40,
    fat: 12,
    fiber: 2,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Linguine", "Karides", "Midye", "Istiridye", "Domates", "Sarımsak"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pasta_008",
    name: "Pappardelle Cinghiale",
    category: "Pastalar",
    subcategory: "Etli Soslu Pastalar",
    description: "Yaban domuzu eti ile yapılan zengin pasta",
    calories: 480,
    protein: 26,
    carbs: 42,
    fat: 22,
    fiber: 2,
    sugar: 2,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Pappardelle", "Yaban Domuzu", "Domates", "Şarap", "Zeytin Yağı"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pasta_009",
    name: "Orzo Risotto",
    category: "Pastalar",
    subcategory: "Risotto Benzeri",
    description: "Risotto tarzında pişirilen orzo (arpa şekilli pasta)",
    calories: 340,
    protein: 12,
    carbs: 45,
    fat: 10,
    fiber: 3,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Orzo", "Sebzeler", "Peynir", "Zeytin Yağı", "Sebze Suyu"],
    healthBenefits: ["Lif kaynağı", "Vitamin"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_pasta_010",
    name: "Gnocchi Gorgonzola",
    category: "Pastalar",
    subcategory: "Patates Ürünleri",
    description: "Gorgonzola peyniri ile yapılan patates gnocchi",
    calories: 360,
    protein: 14,
    carbs: 38,
    fat: 16,
    fiber: 2,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Patates", "Un", "Gorgonzola", "Tereyağı", "Ceviz"],
    healthBenefits: ["Potasyum", "Kalsiyum"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== PİZZALAR =====
export const ITALIAN_PIZZA: ItalianFood[] = [
  {
    id: "it_pizza_001",
    name: "Margherita Pizza",
    category: "Pizzalar",
    subcategory: "Klasik Pizzalar",
    description: "Domates, mozzarella ve fesleğen ile yapılan klasik pizza",
    calories: 280,
    protein: 12,
    carbs: 32,
    fat: 12,
    fiber: 2,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Domates", "Mozzarella", "Fesleğen", "Zeytin Yağı"],
    healthBenefits: ["Kalsiyum", "Lif"],
    warnings: ["Orta kalori"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_pizza_002",
    name: "Quattro Formaggi",
    category: "Pizzalar",
    subcategory: "Peynirli Pizzalar",
    description: "Dört çeşit peynir ile yapılan zengin pizza",
    calories: 320,
    protein: 16,
    carbs: 28,
    fat: 18,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Mozzarella", "Gorgonzola", "Ricotta", "Parmesan"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_pizza_003",
    name: "Pepperoni Pizza",
    category: "Pizzalar",
    subcategory: "Etli Pizzalar",
    description: "Pepperoni ve mozzarella ile yapılan pizza",
    calories: 340,
    protein: 14,
    carbs: 30,
    fat: 18,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Domates", "Mozzarella", "Pepperoni", "Zeytin Yağı"],
    healthBenefits: ["Protein"],
    warnings: ["Yüksek yağ", "Yüksek sodyum"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pizza_004",
    name: "Vegetariana",
    category: "Pizzalar",
    subcategory: "Sebzeli Pizzalar",
    description: "Çeşitli sebzeler ile yapılan pizza",
    calories: 240,
    protein: 10,
    carbs: 32,
    fat: 8,
    fiber: 4,
    sugar: 3,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Domates", "Mozzarella", "Patlıcan", "Biber", "Zucchini"],
    healthBenefits: ["Lif kaynağı", "Vitamin", "Mineral"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_pizza_005",
    name: "Prosciutto e Rucola",
    category: "Pizzalar",
    subcategory: "Etli Pizzalar",
    description: "Prosciutto ve roka ile yapılan pizza",
    calories: 300,
    protein: 14,
    carbs: 28,
    fat: 14,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Domates", "Mozzarella", "Prosciutto", "Roka", "Zeytin Yağı"],
    healthBenefits: ["Protein", "Vitamin K"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pizza_006",
    name: "Diavola",
    category: "Pizzalar",
    subcategory: "Acı Pizzalar",
    description: "Acı pepperoni ve acı biber ile yapılan pizza",
    calories: 320,
    protein: 13,
    carbs: 30,
    fat: 16,
    fiber: 2,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Domates", "Mozzarella", "Acı Pepperoni", "Acı Biber"],
    healthBenefits: ["Protein", "Antioksidan"],
    warnings: ["Yüksek yağ", "Acı"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pizza_007",
    name: "Bianca",
    category: "Pizzalar",
    subcategory: "Beyaz Pizzalar",
    description: "Domates olmadan peynir ve zeytin yağı ile yapılan pizza",
    calories: 300,
    protein: 14,
    carbs: 28,
    fat: 14,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Mozzarella", "Ricotta", "Parmesan", "Zeytin Yağı", "Sarımsak"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_pizza_008",
    name: "Siciliana",
    category: "Pizzalar",
    subcategory: "Bölgesel Pizzalar",
    description: "Sicilya tarzı kalın hamurlu pizza",
    calories: 350,
    protein: 13,
    carbs: 40,
    fat: 16,
    fiber: 2,
    sugar: 2,
    servingSize: 120,
    servingUnit: "g",
    ingredients: ["Hamur", "Domates", "Mozzarella", "Acı Pepperoni", "Soğan"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek kalori"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pizza_009",
    name: "Capricciosa",
    category: "Pizzalar",
    subcategory: "Karışık Pizzalar",
    description: "Çeşitli malzemeler ile yapılan pizza",
    calories: 310,
    protein: 13,
    carbs: 32,
    fat: 14,
    fiber: 2,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Domates", "Mozzarella", "Jambon", "Mantar", "Zeytin"],
    healthBenefits: ["Çeşitli vitamin ve mineral"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_pizza_010",
    name: "Calzone",
    category: "Pizzalar",
    subcategory: "Kapalı Pizzalar",
    description: "İçi dolgulu kapalı pizza",
    calories: 380,
    protein: 16,
    carbs: 38,
    fat: 18,
    fiber: 2,
    sugar: 1,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Hamur", "Mozzarella", "Ricotta", "Jambon", "Ispanak"],
    healthBenefits: ["Protein", "Kalsiyum"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== RİZOTTO =====
export const ITALIAN_RISOTTO: ItalianFood[] = [
  {
    id: "it_risotto_001",
    name: "Risotto Milanese",
    category: "Risotto",
    subcategory: "Klasik Risotto",
    description: "Safran ile yapılan Milano tarzı risotto",
    calories: 380,
    protein: 12,
    carbs: 48,
    fat: 14,
    fiber: 2,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Arborio Pirinç", "Safran", "Şarap", "Peynir", "Tereyağı"],
    healthBenefits: ["Enerji", "Kalsiyum"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_risotto_002",
    name: "Risotto ai Funghi",
    category: "Risotto",
    subcategory: "Mantar Risotto",
    description: "Mantar ile yapılan risotto",
    calories: 320,
    protein: 11,
    carbs: 45,
    fat: 10,
    fiber: 3,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Arborio Pirinç", "Mantar", "Şarap", "Peynir", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Vitamin D"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_risotto_003",
    name: "Risotto ai Frutti di Mare",
    category: "Risotto",
    subcategory: "Deniz Ürünlü Risotto",
    description: "Deniz ürünleri ile yapılan risotto",
    calories: 360,
    protein: 18,
    carbs: 42,
    fat: 12,
    fiber: 2,
    sugar: 0,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Arborio Pirinç", "Karides", "Midye", "Balık", "Şarap"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_risotto_004",
    name: "Risotto Nero",
    category: "Risotto",
    subcategory: "Mürekkep Balığı Risotto",
    description: "Mürekkep balığı mürekkebi ile yapılan siyah risotto",
    calories: 340,
    protein: 16,
    carbs: 42,
    fat: 11,
    fiber: 2,
    sugar: 0,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Arborio Pirinç", "Mürekkep Balığı", "Mürekkep", "Şarap", "Peynir"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_risotto_005",
    name: "Risotto Asparagi",
    category: "Risotto",
    subcategory: "Sebzeli Risotto",
    description: "Kuşkonmaz ile yapılan risotto",
    calories: 300,
    protein: 10,
    carbs: 44,
    fat: 9,
    fiber: 3,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Arborio Pirinç", "Kuşkonmaz", "Şarap", "Peynir", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Folat"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== ANTEPASTO (BAŞLANGIÇLAR) =====
export const ITALIAN_APPETIZERS: ItalianFood[] = [
  {
    id: "it_app_001",
    name: "Bruschetta Pomodoro",
    category: "Başlangıçlar",
    subcategory: "Bruschetta",
    description: "Domates ve fesleğen ile yapılan bruschetta",
    calories: 120,
    protein: 4,
    carbs: 16,
    fat: 5,
    fiber: 2,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Ekmek", "Domates", "Fesleğen", "Sarımsak", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "it_app_002",
    name: "Caprese",
    category: "Başlangıçlar",
    subcategory: "Salatalar",
    description: "Domates, mozzarella ve fesleğen salatası",
    calories: 150,
    protein: 8,
    carbs: 6,
    fat: 11,
    fiber: 1,
    sugar: 3,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Domates", "Mozzarella", "Fesleğen", "Zeytin Yağı", "Tuz"],
    healthBenefits: ["Kalsiyum", "Licopene"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_app_003",
    name: "Calamari Fritti",
    category: "Başlangıçlar",
    subcategory: "Kızartmalar",
    description: "Kızartılmış mürekkep balığı",
    calories: 280,
    protein: 20,
    carbs: 18,
    fat: 14,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Mürekkep Balığı", "Un", "Yağ", "Limon", "Tuz"],
    healthBenefits: ["Protein kaynağı", "Selenium"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_app_004",
    name: "Arancini",
    category: "Başlangıçlar",
    subcategory: "Pirinç Topları",
    description: "Pirinç ve ragù ile dolgulu kızartılmış toplar",
    calories: 240,
    protein: 8,
    carbs: 28,
    fat: 11,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Pirinç", "Ragù", "Peynir", "Yumurta", "Yağ"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_app_005",
    name: "Mozzarella Fresca",
    category: "Başlangıçlar",
    subcategory: "Peynirler",
    description: "Taze mozzarella peyniri",
    calories: 280,
    protein: 28,
    carbs: 3,
    fat: 17,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Mozzarella", "Tuz", "Su"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== SECONDI (ANA YEMEKLER) =====
export const ITALIAN_MAIN_COURSES: ItalianFood[] = [
  {
    id: "it_main_001",
    name: "Osso Buco",
    category: "Ana Yemekler",
    subcategory: "Etli Yemekler",
    description: "Kemikli dana şnitzeli ve gremolata ile",
    calories: 420,
    protein: 38,
    carbs: 12,
    fat: 22,
    fiber: 2,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Dana Şnitzel", "Domates", "Şarap", "Sebzeler", "Gremolata"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_main_002",
    name: "Saltimbocca alla Romana",
    category: "Ana Yemekler",
    subcategory: "Etli Yemekler",
    description: "Prosciutto ve adaçayı ile pişirilen dana eti",
    calories: 320,
    protein: 32,
    carbs: 8,
    fat: 16,
    fiber: 1,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Dana Eti", "Prosciutto", "Adaçayı", "Şarap", "Tereyağı"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_main_003",
    name: "Branzino al Forno",
    category: "Ana Yemekler",
    subcategory: "Balık Yemekleri",
    description: "Fırında pişirilen çipura balığı",
    calories: 280,
    protein: 32,
    carbs: 6,
    fat: 14,
    fiber: 1,
    sugar: 0,
    servingSize: 180,
    servingUnit: "g",
    ingredients: ["Çipura", "Limon", "Zeytin Yağı", "Otlar", "Tuz"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_main_004",
    name: "Vitello Tonnato",
    category: "Ana Yemekler",
    subcategory: "Etli Yemekler",
    description: "Ton balığı sosu ile servis edilen soğuk dana eti",
    calories: 300,
    protein: 34,
    carbs: 4,
    fat: 16,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Dana Eti", "Ton Balığı", "Mayonez", "Kapari", "Anşoa"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "it_main_005",
    name: "Polpo alla Griglia",
    category: "Ana Yemekler",
    subcategory: "Deniz Ürünleri",
    description: "Izgarada pişirilen ahtapot",
    calories: 200,
    protein: 28,
    carbs: 4,
    fat: 8,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Ahtapot", "Zeytin Yağı", "Limon", "Sarımsak", "Kırmızı Biber"],
    healthBenefits: ["Protein kaynağı", "Düşük yağ"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== CONTORNI (YANLAR) =====
export const ITALIAN_SIDES: ItalianFood[] = [
  {
    id: "it_side_001",
    name: "Patatine Fritte",
    category: "Yanlar",
    subcategory: "Kızartmalar",
    description: "Kızartılmış patates çubukları",
    calories: 320,
    protein: 4,
    carbs: 36,
    fat: 18,
    fiber: 3,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Patates", "Yağ", "Tuz"],
    healthBenefits: ["Potasyum"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "it_side_002",
    name: "Verdure Grigliate",
    category: "Yanlar",
    subcategory: "Izgara Sebzeler",
    description: "Izgarada pişirilen çeşitli sebzeler",
    calories: 120,
    protein: 4,
    carbs: 16,
    fat: 5,
    fiber: 4,
    sugar: 2,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Zucchini", "Patlıcan", "Biber", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Vitamin"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "it_side_003",
    name: "Polenta",
    category: "Yanlar",
    subcategory: "Mısır Ürünleri",
    description: "Mısır unu ile yapılan polenta",
    calories: 180,
    protein: 4,
    carbs: 32,
    fat: 4,
    fiber: 2,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Mısır Unu", "Su", "Tuz", "Tereyağı"],
    healthBenefits: ["Enerji", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== DOLCI (TATLILER) =====
export const ITALIAN_DESSERTS: ItalianFood[] = [
  {
    id: "it_dessert_001",
    name: "Tiramisu",
    category: "Tatlılar",
    subcategory: "Klasik Tatlılar",
    description: "Mascarpone ve kahve ile yapılan tatlı",
    calories: 320,
    protein: 6,
    carbs: 32,
    fat: 18,
    fiber: 0,
    sugar: 28,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Mascarpone", "Kahve", "Kakao", "Yumurta", "Şeker"],
    healthBenefits: [],
    warnings: ["Yüksek şeker", "Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_dessert_002",
    name: "Panna Cotta",
    category: "Tatlılar",
    subcategory: "Krem Tatlıları",
    description: "Krema ile yapılan hafif tatlı",
    calories: 280,
    protein: 4,
    carbs: 24,
    fat: 20,
    fiber: 0,
    sugar: 24,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Krema", "Şeker", "Vanilya", "Jelatin"],
    healthBenefits: [],
    warnings: ["Yüksek şeker", "Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_dessert_003",
    name: "Panettone",
    category: "Tatlılar",
    subcategory: "Tatılı Ekmekler",
    description: "Kuru meyve ile yapılan İtalyan Noel keki",
    calories: 340,
    protein: 6,
    carbs: 52,
    fat: 12,
    fiber: 2,
    sugar: 40,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Şeker", "Kuru Meyve", "Yumurta", "Tereyağı"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_dessert_004",
    name: "Gelato",
    category: "Tatlılar",
    subcategory: "Dondurma",
    description: "İtalyan dondurması",
    calories: 240,
    protein: 4,
    carbs: 28,
    fat: 12,
    fiber: 0,
    sugar: 26,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Süt", "Krema", "Şeker", "Yumurta", "Çeşitli Tatlandırıcılar"],
    healthBenefits: ["Kalsiyum"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "it_dessert_005",
    name: "Amaretti",
    category: "Tatlılar",
    subcategory: "Bisküviler",
    description: "Badem ve şeker ile yapılan bisküvi",
    calories: 380,
    protein: 8,
    carbs: 42,
    fat: 20,
    fiber: 2,
    sugar: 38,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Badem", "Şeker", "Yumurta", "Vanilya"],
    healthBenefits: ["Protein"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== TÜM GIDALAR =====
export const ALL_ITALIAN_FOODS: ItalianFood[] = [
  ...ITALIAN_PASTA,
  ...ITALIAN_PIZZA,
  ...ITALIAN_RISOTTO,
  ...ITALIAN_APPETIZERS,
  ...ITALIAN_MAIN_COURSES,
  ...ITALIAN_SIDES,
  ...ITALIAN_DESSERTS,
];

export const ITALIAN_STATISTICS = {
  totalFoods: ALL_ITALIAN_FOODS.length,
  recommendedFoods: ALL_ITALIAN_FOODS.filter(f => f.isRecommended).length,
  diabeticFriendly: ALL_ITALIAN_FOODS.filter(f => f.isDiabeticFriendly).length,
  glutenFree: ALL_ITALIAN_FOODS.filter(f => f.isGlutenFree).length,
  vegetarian: ALL_ITALIAN_FOODS.filter(f => f.isVegetarian).length,
  vegan: ALL_ITALIAN_FOODS.filter(f => f.isVegan).length,
};
