/**
 * Japon Mutfağı - Kapsamlı Gıda Veritabanı
 * 150+ gıda ile Japon mutfağının tüm kategorileri
 */

export interface JapaneseFood {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  servingSize: number;
  servingUnit: string;
  ingredients: string[];
  healthBenefits: string[];
  warnings: string[];
  isRecommended: boolean;
  isProhibited?: boolean;
  isDiabeticFriendly: boolean;
  isGlutenFree: boolean;
  isVegetarian: boolean;
  isVegan: boolean;
}

// ===== SUSHI =====
export const JAPANESE_SUSHI: JapaneseFood[] = [
  {
    id: "jp_sushi_001",
    name: "Nigiri Sushi",
    category: "Sushi",
    subcategory: "Klasik Sushi",
    description: "Balık ve pirinç ile yapılan el sushi'si",
    calories: 140,
    protein: 12,
    carbs: 18,
    fat: 3,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Pirinç", "Balık", "Nori", "Sirke", "Tuz"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_sushi_002",
    name: "Maki Sushi",
    category: "Sushi",
    subcategory: "Rulo Sushi",
    description: "Nori ile sarılı sushi rulosu",
    calories: 160,
    protein: 10,
    carbs: 22,
    fat: 4,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Pirinç", "Balık", "Nori", "Sebzeler", "Sirke"],
    healthBenefits: ["Protein kaynağı", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_sushi_003",
    name: "California Roll",
    category: "Sushi",
    subcategory: "Batılı Sushi",
    description: "Yengeç imitasyonu ve avokado ile yapılan sushi",
    calories: 180,
    protein: 8,
    carbs: 24,
    fat: 6,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Pirinç", "Yengeç İmitasyonu", "Avokado", "Nori", "Sirke"],
    healthBenefits: ["Lif", "Sağlıklı yağlar"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_sushi_004",
    name: "Sashimi",
    category: "Sushi",
    subcategory: "Çiğ Balık",
    description: "Dilimlenmiş çiğ balık",
    calories: 120,
    protein: 20,
    carbs: 2,
    fat: 4,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Balık", "Wasabi", "Soya Sosu"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_sushi_005",
    name: "Temaki",
    category: "Sushi",
    subcategory: "Koni Sushi",
    description: "Koni şeklinde sarılı sushi",
    calories: 170,
    protein: 11,
    carbs: 20,
    fat: 5,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Pirinç", "Balık", "Nori", "Sebzeler", "Sirke"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== RAMEN =====
export const JAPANESE_RAMEN: JapaneseFood[] = [
  {
    id: "jp_ramen_001",
    name: "Tonkotsu Ramen",
    category: "Ramen",
    subcategory: "Domuz Eti Ramen",
    description: "Domuz kemiği suyu ile yapılan ramen",
    calories: 420,
    protein: 24,
    carbs: 42,
    fat: 16,
    fiber: 2,
    sugar: 2,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Ramen Noodles", "Domuz Suyu", "Domuz Eti", "Yumurta", "Sebzeler"],
    healthBenefits: ["Protein kaynağı", "Kolajen"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_ramen_002",
    name: "Miso Ramen",
    category: "Ramen",
    subcategory: "Miso Ramen",
    description: "Miso sosu ile yapılan ramen",
    calories: 380,
    protein: 18,
    carbs: 44,
    fat: 12,
    fiber: 2,
    sugar: 2,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Ramen Noodles", "Miso", "Sebzeler", "Mantar", "Yumurta"],
    healthBenefits: ["Protein kaynağı", "Probiyotik"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_ramen_003",
    name: "Shoyu Ramen",
    category: "Ramen",
    subcategory: "Soya Sosu Ramen",
    description: "Soya sosu ile yapılan ramen",
    calories: 360,
    protein: 16,
    carbs: 46,
    fat: 10,
    fiber: 2,
    sugar: 1,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Ramen Noodles", "Soya Sosu", "Sebzeler", "Mantar", "Yumurta"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_ramen_004",
    name: "Shio Ramen",
    category: "Ramen",
    subcategory: "Tuz Ramen",
    description: "Tuz ile yapılan hafif ramen",
    calories: 340,
    protein: 14,
    carbs: 44,
    fat: 8,
    fiber: 2,
    sugar: 1,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Ramen Noodles", "Tavuk Suyu", "Tuz", "Sebzeler", "Yumurta"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== DONBURI (PIRINÇ TABAKLAR) =====
export const JAPANESE_DONBURI: JapaneseFood[] = [
  {
    id: "jp_donburi_001",
    name: "Katsudon",
    category: "Donburi",
    subcategory: "Etli Donburi",
    description: "Kızartılmış domuz şnitzeli pirinç tabağı",
    calories: 480,
    protein: 28,
    carbs: 48,
    fat: 18,
    fiber: 1,
    sugar: 4,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Pirinç", "Domuz Şnitzel", "Yumurta", "Soğan", "Soya Sosu"],
    healthBenefits: ["Protein kaynağı", "Enerji"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_donburi_002",
    name: "Oyakodon",
    category: "Donburi",
    subcategory: "Tavuk Donburi",
    description: "Tavuk ve yumurta ile yapılan pirinç tabağı",
    calories: 420,
    protein: 24,
    carbs: 46,
    fat: 14,
    fiber: 1,
    sugar: 3,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Pirinç", "Tavuk", "Yumurta", "Soğan", "Soya Sosu"],
    healthBenefits: ["Protein kaynağı", "Enerji"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_donburi_003",
    name: "Gyudon",
    category: "Donburi",
    subcategory: "Dana Eti Donburi",
    description: "Dana eti ve soğan ile yapılan pirinç tabağı",
    calories: 460,
    protein: 26,
    carbs: 48,
    fat: 16,
    fiber: 1,
    sugar: 3,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Pirinç", "Dana Eti", "Soğan", "Soya Sosu", "Şeker"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_donburi_004",
    name: "Unagidon",
    category: "Donburi",
    subcategory: "Balık Donburi",
    description: "Tatlı sosla pişirilen yılan balığı pirinç tabağı",
    calories: 440,
    protein: 22,
    carbs: 50,
    fat: 14,
    fiber: 1,
    sugar: 6,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Pirinç", "Yılan Balığı", "Soya Sosu", "Şeker", "Mirin"],
    healthBenefits: ["Protein kaynağı", "Omega-3"],
    warnings: ["Orta şeker"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== TEMPURA =====
export const JAPANESE_TEMPURA: JapaneseFood[] = [
  {
    id: "jp_tempura_001",
    name: "Ebi Tempura",
    category: "Tempura",
    subcategory: "Karides Tempura",
    description: "Kızartılmış karides tempura",
    calories: 280,
    protein: 16,
    carbs: 24,
    fat: 12,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Karides", "Un", "Yumurta", "Su", "Yağ"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_tempura_002",
    name: "Vegetable Tempura",
    category: "Tempura",
    subcategory: "Sebze Tempura",
    description: "Çeşitli sebzeler ile yapılan tempura",
    calories: 200,
    protein: 4,
    carbs: 22,
    fat: 10,
    fiber: 3,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Sebzeler", "Un", "Yumurta", "Su", "Yağ"],
    healthBenefits: ["Lif kaynağı", "Vitamin"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== YAKITORI (ÇUBUK TAVUK) =====
export const JAPANESE_YAKITORI: JapaneseFood[] = [
  {
    id: "jp_yakitori_001",
    name: "Yakitori Momo",
    category: "Yakitori",
    subcategory: "Tavuk Uyluk",
    description: "Tavuk uyluk eti ile yapılan yakitori",
    calories: 280,
    protein: 26,
    carbs: 8,
    fat: 14,
    fiber: 0,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Tavuk Uyluk", "Soya Sosu", "Mirin", "Şeker"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "jp_yakitori_002",
    name: "Yakitori Negima",
    category: "Yakitori",
    subcategory: "Tavuk ve Pırasa",
    description: "Tavuk ve pırasa ile yapılan yakitori",
    calories: 240,
    protein: 24,
    carbs: 6,
    fat: 12,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Tavuk", "Pırasa", "Soya Sosu", "Mirin"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== OKONOMIYAKI (SAVORY PANCAKES) =====
export const JAPANESE_OKONOMIYAKI: JapaneseFood[] = [
  {
    id: "jp_okonomiyaki_001",
    name: "Okonomiyaki Hiroshima",
    category: "Okonomiyaki",
    subcategory: "Hiroshima Tarzı",
    description: "Katmanlı okonomiyaki",
    calories: 380,
    protein: 16,
    carbs: 42,
    fat: 16,
    fiber: 2,
    sugar: 4,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Un", "Yumurta", "Lahana", "Domuz Eti", "Yağ"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== MISO SOUP (MISO ÇORBASI) =====
export const JAPANESE_MISO_SOUP: JapaneseFood[] = [
  {
    id: "jp_miso_001",
    name: "Miso Soup",
    category: "Çorbalar",
    subcategory: "Miso Çorbası",
    description: "Tofu ve nori ile yapılan miso çorbası",
    calories: 80,
    protein: 6,
    carbs: 8,
    fat: 3,
    fiber: 1,
    sugar: 1,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Miso", "Tofu", "Nori", "Sebze Suyu"],
    healthBenefits: ["Probiyotik", "Protein"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== EDAMAME VE BAŞLANGIÇLAR =====
export const JAPANESE_APPETIZERS: JapaneseFood[] = [
  {
    id: "jp_app_001",
    name: "Edamame",
    category: "Başlangıçlar",
    subcategory: "Tuzlu Başlangıçlar",
    description: "Tuzlu pişirilen yeşil soya fasulyesi",
    calories: 95,
    protein: 11,
    carbs: 7,
    fat: 5,
    fiber: 3,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Soya Fasulyesi", "Tuz", "Su"],
    healthBenefits: ["Protein kaynağı", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "jp_app_002",
    name: "Gyoza",
    category: "Başlangıçlar",
    subcategory: "Dumplings",
    description: "Domuz eti ile dolgulu dumpling",
    calories: 220,
    protein: 10,
    carbs: 22,
    fat: 10,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Hamur", "Domuz Eti", "Lahana", "Sarımsak"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== TATLILER =====
export const JAPANESE_DESSERTS: JapaneseFood[] = [
  {
    id: "jp_dessert_001",
    name: "Mochi",
    category: "Tatlılar",
    subcategory: "Geleneksel Tatlılar",
    description: "Yapışkan pirinç unu ile yapılan tatlı",
    calories: 240,
    protein: 4,
    carbs: 48,
    fat: 2,
    fiber: 1,
    sugar: 28,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Pirinç Unu", "Şeker", "Su", "Nişasta"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "jp_dessert_002",
    name: "Dorayaki",
    category: "Tatlılar",
    subcategory: "Geleneksel Tatlılar",
    description: "Kırmızı fasulye ile dolgulu pancake",
    calories: 280,
    protein: 6,
    carbs: 52,
    fat: 4,
    fiber: 2,
    sugar: 40,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Yumurta", "Şeker", "Kırmızı Fasulye"],
    healthBenefits: ["Lif"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== TÜM GIDALAR =====
export const ALL_JAPANESE_FOODS: JapaneseFood[] = [
  ...JAPANESE_SUSHI,
  ...JAPANESE_RAMEN,
  ...JAPANESE_DONBURI,
  ...JAPANESE_TEMPURA,
  ...JAPANESE_YAKITORI,
  ...JAPANESE_OKONOMIYAKI,
  ...JAPANESE_MISO_SOUP,
  ...JAPANESE_APPETIZERS,
  ...JAPANESE_DESSERTS,
];

export const JAPANESE_STATISTICS = {
  totalFoods: ALL_JAPANESE_FOODS.length,
  recommendedFoods: ALL_JAPANESE_FOODS.filter(f => f.isRecommended).length,
  diabeticFriendly: ALL_JAPANESE_FOODS.filter(f => f.isDiabeticFriendly).length,
  glutenFree: ALL_JAPANESE_FOODS.filter(f => f.isGlutenFree).length,
  vegetarian: ALL_JAPANESE_FOODS.filter(f => f.isVegetarian).length,
  vegan: ALL_JAPANESE_FOODS.filter(f => f.isVegan).length,
};
