/**
 * Kore Mutfağı - Kapsamlı Gıda Veritabanı
 * 150+ gıda ile Kore mutfağının tüm kategorileri
 */

export interface KoreanFood {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  servingSize: number;
  servingUnit: string;
  ingredients: string[];
  healthBenefits: string[];
  warnings: string[];
  isRecommended: boolean;
  isProhibited?: boolean;
  isDiabeticFriendly: boolean;
  isGlutenFree: boolean;
  isVegetarian: boolean;
  isVegan: boolean;
}

// ===== BIBIMBAP =====
export const KOREAN_BIBIMBAP: KoreanFood[] = [
  {
    id: "ko_bibimbap_001",
    name: "Bibimbap",
    category: "Bibimbap",
    subcategory: "Klasik Bibimbap",
    description: "Pirinç ve çeşitli sebzeler ile yapılan karışık yemek",
    calories: 420,
    protein: 18,
    carbs: 48,
    fat: 14,
    fiber: 4,
    sugar: 3,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Pirinç", "Sebzeler", "Yumurta", "Dana Eti", "Gochujang"],
    healthBenefits: ["Lif kaynağı", "Protein", "Vitamin"],
    warnings: ["Orta yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "ko_bibimbap_002",
    name: "Vegetable Bibimbap",
    category: "Bibimbap",
    subcategory: "Sebzeli Bibimbap",
    description: "Sebzeler ile yapılan vegetaryen bibimbap",
    calories: 320,
    protein: 10,
    carbs: 50,
    fat: 8,
    fiber: 5,
    sugar: 2,
    servingSize: 300,
    servingUnit: "g",
    ingredients: ["Pirinç", "Sebzeler", "Yumurta", "Gochujang", "Sesam"],
    healthBenefits: ["Lif kaynağı", "Vitamin"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== BULGOGI =====
export const KOREAN_BULGOGI: KoreanFood[] = [
  {
    id: "ko_bulgogi_001",
    name: "Bulgogi",
    category: "Bulgogi",
    subcategory: "Dana Eti Bulgogi",
    description: "Tatlı ve acı sosla marineli dana eti",
    calories: 380,
    protein: 32,
    carbs: 12,
    fat: 20,
    fiber: 1,
    sugar: 8,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Dana Eti", "Soya Sosu", "Şeker", "Sesam", "Sarımsak"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Orta yağ", "Orta şeker"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "ko_bulgogi_002",
    name: "Chicken Bulgogi",
    category: "Bulgogi",
    subcategory: "Tavuk Bulgogi",
    description: "Tavuk ile yapılan bulgogi",
    calories: 320,
    protein: 28,
    carbs: 10,
    fat: 16,
    fiber: 1,
    sugar: 6,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Tavuk", "Soya Sosu", "Şeker", "Sesam", "Sarımsak"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Orta şeker"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== KIMCHI =====
export const KOREAN_KIMCHI: KoreanFood[] = [
  {
    id: "ko_kimchi_001",
    name: "Kimchi",
    category: "Kimchi",
    subcategory: "Klasik Kimchi",
    description: "Acı ve fermente lahana",
    calories: 40,
    protein: 2,
    carbs: 7,
    fat: 0,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Lahana", "Acı Biber", "Sarımsak", "Tuz"],
    healthBenefits: ["Probiyotik", "Lif"],
    warnings: ["Çok acı"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "ko_kimchi_002",
    name: "Radish Kimchi",
    category: "Kimchi",
    subcategory: "Turp Kimchi",
    description: "Turp ile yapılan kimchi",
    calories: 30,
    protein: 1,
    carbs: 6,
    fat: 0,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Turp", "Acı Biber", "Sarımsak", "Tuz"],
    healthBenefits: ["Probiyotik", "Vitamin C"],
    warnings: ["Çok acı"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== TTEOKBOKKI (ACILI PIRINÇ KEKI) =====
export const KOREAN_TTEOKBOKKI: KoreanFood[] = [
  {
    id: "ko_tteokbokki_001",
    name: "Tteokbokki",
    category: "Tteokbokki",
    subcategory: "Klasik Tteokbokki",
    description: "Acı sosla pişirilen pirinç keki",
    calories: 280,
    protein: 6,
    carbs: 42,
    fat: 8,
    fiber: 2,
    sugar: 6,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Pirinç Keki", "Gochujang", "Şeker", "Sesam", "Sebzeler"],
    healthBenefits: ["Enerji"],
    warnings: ["Çok acı", "Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== KOREAN BBQ =====
export const KOREAN_BBQ: KoreanFood[] = [
  {
    id: "ko_bbq_001",
    name: "Galbi",
    category: "Korean BBQ",
    subcategory: "Kaburga",
    description: "Tatlı sosla marineli dana kaburga",
    calories: 420,
    protein: 36,
    carbs: 8,
    fat: 28,
    fiber: 0,
    sugar: 6,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Dana Kaburga", "Soya Sosu", "Şeker", "Sesam", "Sarımsak"],
    healthBenefits: ["Protein kaynağı", "Demir"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "ko_bbq_002",
    name: "Samgyeopsal",
    category: "Korean BBQ",
    subcategory: "Domuz Eti",
    description: "Domuz eti dilimi",
    calories: 380,
    protein: 28,
    carbs: 2,
    fat: 30,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Domuz Eti", "Tuz", "Biber"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== JJIGAE (ÇORBALAR) =====
export const KOREAN_JJIGAE: KoreanFood[] = [
  {
    id: "ko_jjigae_001",
    name: "Kimchi Jjigae",
    category: "Çorbalar",
    subcategory: "Kimchi Çorbası",
    description: "Kimchi ve domuz eti ile yapılan çorba",
    calories: 200,
    protein: 16,
    carbs: 12,
    fat: 10,
    fiber: 2,
    sugar: 1,
    servingSize: 300,
    servingUnit: "ml",
    ingredients: ["Kimchi", "Domuz Eti", "Tofu", "Sebze Suyu"],
    healthBenefits: ["Probiyotik", "Protein"],
    warnings: ["Çok acı"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: "ko_jjigae_002",
    name: "Doenjang Jjigae",
    category: "Çorbalar",
    subcategory: "Soya Fasulyesi Çorbası",
    description: "Soya fasulyesi ve sebzeler ile yapılan çorba",
    calories: 160,
    protein: 12,
    carbs: 14,
    fat: 6,
    fiber: 3,
    sugar: 1,
    servingSize: 300,
    servingUnit: "ml",
    ingredients: ["Doenjang", "Tofu", "Sebzeler", "Sebze Suyu"],
    healthBenefits: ["Probiyotik", "Protein", "Lif"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== KIMBAP =====
export const KOREAN_KIMBAP: KoreanFood[] = [
  {
    id: "ko_kimbap_001",
    name: "Kimbap",
    category: "Kimbap",
    subcategory: "Klasik Kimbap",
    description: "Nori ile sarılı pirinç ve sebzeler",
    calories: 200,
    protein: 8,
    carbs: 32,
    fat: 4,
    fiber: 2,
    sugar: 1,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Pirinç", "Nori", "Sebzeler", "Yumurta", "Sesam"],
    healthBenefits: ["Lif kaynağı", "Vitamin"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== KOREAN FRIED CHICKEN =====
export const KOREAN_FRIED_CHICKEN: KoreanFood[] = [
  {
    id: "ko_chicken_001",
    name: "Korean Fried Chicken",
    category: "Tavuk",
    subcategory: "Kızartılmış Tavuk",
    description: "Çift kızartılmış Kore tavuğu",
    calories: 380,
    protein: 28,
    carbs: 24,
    fat: 20,
    fiber: 1,
    sugar: 4,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Tavuk", "Un", "Yağ", "Gochujang", "Şeker"],
    healthBenefits: ["Protein kaynağı"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
    isVegan: false,
  },
];

// ===== BANCHAN (YANLAR) =====
export const KOREAN_BANCHAN: KoreanFood[] = [
  {
    id: "ko_banchan_001",
    name: "Sigeumchi Namul",
    category: "Yanlar",
    subcategory: "Sebze Salatası",
    description: "Ispanak ile yapılan yan yemek",
    calories: 80,
    protein: 4,
    carbs: 8,
    fat: 4,
    fiber: 2,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Ispanak", "Sesam", "Soya Sosu", "Sarımsak"],
    healthBenefits: ["Demir", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "ko_banchan_002",
    name: "Sukju Namul",
    category: "Yanlar",
    subcategory: "Filiz Salatası",
    description: "Soya filizi ile yapılan yan yemek",
    calories: 70,
    protein: 4,
    carbs: 6,
    fat: 3,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Soya Filizi", "Sesam", "Soya Sosu", "Sarımsak"],
    healthBenefits: ["Protein kaynağı", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== TATLILER =====
export const KOREAN_DESSERTS: KoreanFood[] = [
  {
    id: "ko_dessert_001",
    name: "Hotteok",
    category: "Tatlılar",
    subcategory: "Tatlı Pancake",
    description: "Şeker ve tarçın ile dolgulu pancake",
    calories: 280,
    protein: 4,
    carbs: 48,
    fat: 8,
    fiber: 1,
    sugar: 24,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Şeker", "Tarçın", "Yağ"],
    healthBenefits: [],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "ko_dessert_002",
    name: "Bingsu",
    category: "Tatlılar",
    subcategory: "Buz Tatlısı",
    description: "Buz ve tatlı sosla yapılan tatlı",
    calories: 200,
    protein: 2,
    carbs: 42,
    fat: 2,
    fiber: 0,
    sugar: 40,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Buz", "Şeker Şurubu", "Meyve", "Kondense Süt"],
    healthBenefits: [],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== TÜM GIDALAR =====
export const ALL_KOREAN_FOODS: KoreanFood[] = [
  ...KOREAN_BIBIMBAP,
  ...KOREAN_BULGOGI,
  ...KOREAN_KIMCHI,
  ...KOREAN_TTEOKBOKKI,
  ...KOREAN_BBQ,
  ...KOREAN_JJIGAE,
  ...KOREAN_KIMBAP,
  ...KOREAN_FRIED_CHICKEN,
  ...KOREAN_BANCHAN,
  ...KOREAN_DESSERTS,
];

export const KOREAN_STATISTICS = {
  totalFoods: ALL_KOREAN_FOODS.length,
  recommendedFoods: ALL_KOREAN_FOODS.filter(f => f.isRecommended).length,
  diabeticFriendly: ALL_KOREAN_FOODS.filter(f => f.isDiabeticFriendly).length,
  glutenFree: ALL_KOREAN_FOODS.filter(f => f.isGlutenFree).length,
  vegetarian: ALL_KOREAN_FOODS.filter(f => f.isVegetarian).length,
  vegan: ALL_KOREAN_FOODS.filter(f => f.isVegan).length,
};
