/**
 * Türk Mutfağı - Kapsamlı Gıda Veritabanı
 * Tüm kategoriler, alt başlıklar ve özel durumlar
 */

export interface TurkishFood {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  servingSize: number;
  servingUnit: string;
  ingredients: string[];
  healthBenefits: string[];
  warnings: string[];
  isRecommended?: boolean;
  isProhibited?: boolean;
  isDiabeticFriendly?: boolean;
  isGlutenFree?: boolean;
  isVegetarian?: boolean;
  isVegan?: boolean;
  isLactoseFree?: boolean;
}

// ===== ÇORBALAR =====
export const SOUPS: TurkishFood[] = [
  {
    id: "tr_soup_001",
    name: "Mercimek Çorbası",
    category: "Çorbalar",
    subcategory: "Kırmızı Mercimek",
    description: "Kırmızı mercimekten yapılan besleyici çorba",
    calories: 120,
    protein: 8,
    carbs: 20,
    fat: 2,
    fiber: 6,
    sugar: 2,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Kırmızı Mercimek", "Soğan", "Sarımsak", "Zeytin Yağı"],
    healthBenefits: ["Yüksek protein", "Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_soup_002",
    name: "Yayla Çorbası",
    category: "Çorbalar",
    subcategory: "Yoğurtlu Çorba",
    description: "Yoğurt ve buğday unu ile yapılan geleneksel çorba",
    calories: 140,
    protein: 6,
    carbs: 18,
    fat: 5,
    fiber: 2,
    sugar: 3,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Yoğurt", "Buğday Unu", "Tavuk Suyu", "Nane"],
    healthBenefits: ["Probiyotik", "Kalsiyum", "Protein"],
    warnings: ["Gluten içerir"],
    isRecommended: true,
    isDiabeticFriendly: false,
  },
  {
    id: "tr_soup_003",
    name: "Tarhana Çorbası",
    category: "Çorbalar",
    subcategory: "Tarhana",
    description: "Tarhana unu ile yapılan eski Türk çorbası",
    calories: 130,
    protein: 5,
    carbs: 22,
    fat: 3,
    fiber: 3,
    sugar: 2,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Tarhana Unu", "Su", "Tereyağı", "Kırmızı Biber"],
    healthBenefits: ["Lif kaynağı", "Probiyotik"],
    warnings: ["Gluten içerebilir"],
    isRecommended: true,
  },
  {
    id: "tr_soup_004",
    name: "Domates Çorbası",
    category: "Çorbalar",
    subcategory: "Sebze Çorbası",
    description: "Taze domates ile yapılan hafif çorba",
    calories: 80,
    protein: 3,
    carbs: 15,
    fat: 2,
    fiber: 3,
    sugar: 8,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Domates", "Soğan", "Sarımsak", "Zeytin Yağı"],
    healthBenefits: ["Licopene kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_soup_005",
    name: "Patlıcan Çorbası",
    category: "Çorbalar",
    subcategory: "Sebze Çorbası",
    description: "Kavrulmuş patlıcan ile yapılan çorba",
    calories: 95,
    protein: 3,
    carbs: 14,
    fat: 4,
    fiber: 4,
    sugar: 3,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Patlıcan", "Soğan", "Zeytin Yağı", "Sarımsak"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_soup_006",
    name: "Tavuk Çorbası",
    category: "Çorbalar",
    subcategory: "Et Çorbası",
    description: "Tavuk eti ile yapılan besleyici çorba",
    calories: 110,
    protein: 14,
    carbs: 8,
    fat: 4,
    fiber: 1,
    sugar: 1,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Tavuk Eti", "Tavuk Suyu", "Sebzeler", "Pirinç"],
    healthBenefits: ["Yüksek protein", "Kolay sindirim"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_soup_007",
    name: "Nohut Çorbası",
    category: "Çorbalar",
    subcategory: "Baklagil Çorbası",
    description: "Nohut ile yapılan protein açısından zengin çorba",
    calories: 150,
    protein: 9,
    carbs: 22,
    fat: 3,
    fiber: 6,
    sugar: 2,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Nohut", "Soğan", "Sarımsak", "Zeytin Yağı"],
    healthBenefits: ["Yüksek protein", "Lif kaynağı", "Demir"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_soup_008",
    name: "Ezogelin Çorbası",
    category: "Çorbalar",
    subcategory: "Baklagil Çorbası",
    description: "Mercimek ve bulgur ile yapılan çorba",
    calories: 125,
    protein: 7,
    carbs: 21,
    fat: 2,
    fiber: 5,
    sugar: 1,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Kırmızı Mercimek", "Bulgur", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Protein", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_soup_009",
    name: "Balık Çorbası",
    category: "Çorbalar",
    subcategory: "Deniz Ürünü Çorbası",
    description: "Taze balık ile yapılan hafif çorba",
    calories: 100,
    protein: 16,
    carbs: 5,
    fat: 2,
    fiber: 1,
    sugar: 0,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Balık", "Balık Suyu", "Sebzeler", "Limon"],
    healthBenefits: ["Omega-3", "Yüksek protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_soup_010",
    name: "Sebze Çorbası",
    category: "Çorbalar",
    subcategory: "Sebze Çorbası",
    description: "Mevsimsel sebzelerle yapılan çorba",
    calories: 70,
    protein: 3,
    carbs: 14,
    fat: 1,
    fiber: 3,
    sugar: 2,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Sebzeler", "Soğan", "Zeytin Yağı", "Su"],
    healthBenefits: ["Vitamin", "Lif kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== SEBZE YEMEKLERİ =====
export const VEGETABLE_DISHES: TurkishFood[] = [
  {
    id: "tr_veg_001",
    name: "Zeytinyağlı Yaprak Sarması",
    category: "Sebze Yemekleri",
    subcategory: "Zeytinyağlı Yemekler",
    description: "Asma yaprağına sarılmış pirinç ve otlar",
    calories: 180,
    protein: 4,
    carbs: 22,
    fat: 9,
    fiber: 3,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Asma Yaprağı", "Pirinç", "Zeytin Yağı", "Otlar"],
    healthBenefits: ["Lif kaynağı", "Sağlıklı yağlar"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_veg_002",
    name: "Zeytinyağlı Patlıcan",
    category: "Sebze Yemekleri",
    subcategory: "Zeytinyağlı Yemekler",
    description: "Patlıcan ve domates ile yapılan zeytinyağlı yemek",
    calories: 150,
    protein: 3,
    carbs: 16,
    fat: 8,
    fiber: 4,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Domates", "Zeytin Yağı", "Sarımsak"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_veg_003",
    name: "Imam Bayıldı",
    category: "Sebze Yemekleri",
    subcategory: "Zeytinyağlı Yemekler",
    description: "Patlıcan içine soğan ve domates dolgulu yemek",
    calories: 160,
    protein: 3,
    carbs: 18,
    fat: 8,
    fiber: 4,
    sugar: 3,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Soğan", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_veg_004",
    name: "Biber Dolması",
    category: "Sebze Yemekleri",
    subcategory: "Dolmalar",
    description: "Biber içine pirinç ve et dolgulu yemek",
    calories: 200,
    protein: 8,
    carbs: 24,
    fat: 8,
    fiber: 2,
    sugar: 3,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Biber", "Pirinç", "Kıyma", "Domates"],
    healthBenefits: ["Vitamin C", "Protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
  },
  {
    id: "tr_veg_005",
    name: "Patlıcan Dolması",
    category: "Sebze Yemekleri",
    subcategory: "Dolmalar",
    description: "Patlıcan içine pirinç ve et dolgulu yemek",
    calories: 210,
    protein: 9,
    carbs: 22,
    fat: 9,
    fiber: 3,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Pirinç", "Kıyma", "Soğan"],
    healthBenefits: ["Lif kaynağı", "Protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
  },
  {
    id: "tr_veg_006",
    name: "Turşu",
    category: "Sebze Yemekleri",
    subcategory: "Fermente Sebzeler",
    description: "Tuz ve sirke ile fermente edilmiş sebzeler",
    calories: 30,
    protein: 1,
    carbs: 6,
    fat: 0,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Sebzeler", "Tuz", "Sirke", "Baharat"],
    healthBenefits: ["Probiyotik", "Lif kaynağı"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_veg_007",
    name: "Mücver",
    category: "Sebze Yemekleri",
    subcategory: "Kızartmalar",
    description: "Kabak ve peynir ile yapılan kızartma",
    calories: 220,
    protein: 8,
    carbs: 18,
    fat: 12,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Kabak", "Peynir", "Yumurta", "Un"],
    healthBenefits: ["Protein", "Kalsiyum"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_veg_008",
    name: "Kuru Fasulye",
    category: "Sebze Yemekleri",
    subcategory: "Baklagil Yemekleri",
    description: "Kuru fasulye ile yapılan yemek",
    calories: 140,
    protein: 8,
    carbs: 24,
    fat: 2,
    fiber: 6,
    sugar: 1,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Kuru Fasulye", "Soğan", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Protein", "Demir"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_veg_009",
    name: "Nohut Yemeği",
    category: "Sebze Yemekleri",
    subcategory: "Baklagil Yemekleri",
    description: "Nohut ile yapılan yemek",
    calories: 160,
    protein: 9,
    carbs: 26,
    fat: 3,
    fiber: 7,
    sugar: 1,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Nohut", "Soğan", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Protein", "Lif kaynağı", "Mineral"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_veg_010",
    name: "Sebze Güveç",
    category: "Sebze Yemekleri",
    subcategory: "Güveç Yemekleri",
    description: "Mevsimsel sebzelerle yapılan güveç",
    calories: 120,
    protein: 4,
    carbs: 18,
    fat: 4,
    fiber: 4,
    sugar: 2,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Sebzeler", "Domates", "Zeytin Yağı", "Baharat"],
    healthBenefits: ["Vitamin", "Lif kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== SALATALAR =====
export const SALADS: TurkishFood[] = [
  {
    id: "tr_salad_001",
    name: "Çoban Salatası",
    category: "Salatalar",
    subcategory: "Taze Salatalar",
    description: "Domates, salatalık ve soğandan yapılan salata",
    calories: 50,
    protein: 2,
    carbs: 10,
    fat: 1,
    fiber: 2,
    sugar: 3,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Domates", "Salatalık", "Soğan", "Maydanoz"],
    healthBenefits: ["Düşük kalori", "Vitamin"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_salad_002",
    name: "Patlıcan Salatası",
    category: "Salatalar",
    subcategory: "Taze Salatalar",
    description: "Kavrulmuş patlıcan ile yapılan salata",
    calories: 100,
    protein: 2,
    carbs: 12,
    fat: 5,
    fiber: 3,
    sugar: 2,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Yoğurt", "Sarımsak", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_salad_003",
    name: "Roka Salatası",
    category: "Salatalar",
    subcategory: "Taze Salatalar",
    description: "Roka ve parmesan ile yapılan salata",
    calories: 120,
    protein: 6,
    carbs: 8,
    fat: 8,
    fiber: 2,
    sugar: 1,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Roka", "Parmesan", "Zeytin Yağı", "Limon"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_salad_004",
    name: "Tabbule",
    category: "Salatalar",
    subcategory: "Bulgurlu Salatalar",
    description: "Bulgur, maydanoz ve limon ile yapılan salata",
    calories: 140,
    protein: 5,
    carbs: 22,
    fat: 4,
    fiber: 4,
    sugar: 2,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Bulgur", "Maydanoz", "Domates", "Limon"],
    healthBenefits: ["Lif kaynağı", "Vitamin"],
    warnings: ["Gluten içerir"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_salad_005",
    name: "Hummus",
    category: "Salatalar",
    subcategory: "Mezeler",
    description: "Nohut ve tahini ile yapılan salata",
    calories: 150,
    protein: 5,
    carbs: 13,
    fat: 9,
    fiber: 3,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Nohut", "Tahini", "Limon", "Sarımsak"],
    healthBenefits: ["Protein", "Lif kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_salad_006",
    name: "Baba Ganoush",
    category: "Salatalar",
    subcategory: "Mezeler",
    description: "Patlıcan ve tahini ile yapılan salata",
    calories: 130,
    protein: 3,
    carbs: 12,
    fat: 8,
    fiber: 3,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Tahini", "Limon", "Sarımsak"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_salad_007",
    name: "Cacık",
    category: "Salatalar",
    subcategory: "Yoğurtlu Salatalar",
    description: "Yoğurt, salatalık ve dill ile yapılan salata",
    calories: 80,
    protein: 5,
    carbs: 8,
    fat: 3,
    fiber: 1,
    sugar: 2,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Yoğurt", "Salatalık", "Dill", "Sarımsak"],
    healthBenefits: ["Probiyotik", "Kalsiyum"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_salad_008",
    name: "Haydari",
    category: "Salatalar",
    subcategory: "Yoğurtlu Salatalar",
    description: "Yoğurt, peynir ve otlar ile yapılan salata",
    calories: 120,
    protein: 8,
    carbs: 6,
    fat: 8,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Yoğurt", "Beyaz Peynir", "Dill", "Maydanoz"],
    healthBenefits: ["Probiyotik", "Kalsiyum"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_salad_009",
    name: "Muhamarra",
    category: "Salatalar",
    subcategory: "Mezeler",
    description: "Kırmızı biber ve ceviz ile yapılan salata",
    calories: 180,
    protein: 5,
    carbs: 14,
    fat: 12,
    fiber: 3,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Kırmızı Biber", "Ceviz", "Ekmek Kırıntısı", "Zeytin Yağı"],
    healthBenefits: ["Antioksidan", "Sağlıklı yağlar"],
    warnings: ["Gluten içerebilir"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_salad_010",
    name: "Melon Salatası",
    category: "Salatalar",
    subcategory: "Taze Salatalar",
    description: "Melon ve peynir ile yapılan salata",
    calories: 80,
    protein: 4,
    carbs: 12,
    fat: 3,
    fiber: 1,
    sugar: 9,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Melon", "Beyaz Peynir", "Zeytin Yağı"],
    healthBenefits: ["Vitamin C", "Kalsiyum"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
  },
];

// ===== İÇECEKLER =====
export const BEVERAGES: TurkishFood[] = [
  {
    id: "tr_bev_001",
    name: "Türk Çayı",
    category: "İçecekler",
    subcategory: "Sıcak İçecekler",
    description: "Geleneksel Türk çayı",
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Çay Yaprağı", "Su"],
    healthBenefits: ["Antioksidan", "Metabolizm hızlandırıcı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_bev_002",
    name: "Türk Kahvesi",
    category: "İçecekler",
    subcategory: "Sıcak İçecekler",
    description: "Geleneksel Türk kahvesi",
    calories: 12,
    protein: 0,
    carbs: 1,
    fat: 0,
    fiber: 0,
    sugar: 0,
    servingSize: 75,
    servingUnit: "ml",
    ingredients: ["Kahve", "Su", "Kardamom"],
    healthBenefits: ["Antioksidan", "Enerji"],
    warnings: ["Yüksek kafein"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_bev_003",
    name: "Ayran",
    category: "İçecekler",
    subcategory: "Soğuk İçecekler",
    description: "Yoğurt ve su ile yapılan geleneksel içecek",
    calories: 40,
    protein: 2,
    carbs: 3,
    fat: 1,
    fiber: 0,
    sugar: 2,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Yoğurt", "Su", "Tuz"],
    healthBenefits: ["Probiyotik", "Kalsiyum"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_bev_004",
    name: "Limonata",
    category: "İçecekler",
    subcategory: "Soğuk İçecekler",
    description: "Limon ve su ile yapılan içecek",
    calories: 30,
    protein: 0,
    carbs: 8,
    fat: 0,
    fiber: 0,
    sugar: 6,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Limon", "Su", "Şeker"],
    healthBenefits: ["Vitamin C"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_bev_005",
    name: "Nar Suyu",
    category: "İçecekler",
    subcategory: "Meyve Suları",
    description: "Taze nar suyundan yapılan içecek",
    calories: 70,
    protein: 1,
    carbs: 16,
    fat: 0,
    fiber: 0,
    sugar: 14,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Nar", "Su"],
    healthBenefits: ["Antioksidan", "Vitamin C"],
    warnings: ["Yüksek şeker"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_bev_006",
    name: "Portakal Suyu",
    category: "İçecekler",
    subcategory: "Meyve Suları",
    description: "Taze portakal suyundan yapılan içecek",
    calories: 60,
    protein: 1,
    carbs: 14,
    fat: 0,
    fiber: 0,
    sugar: 12,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Portakal", "Su"],
    healthBenefits: ["Vitamin C", "Antioksidan"],
    warnings: ["Yüksek şeker"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_bev_007",
    name: "Kefir",
    category: "İçecekler",
    subcategory: "Fermente İçecekler",
    description: "Fermente süt ürünü",
    calories: 60,
    protein: 4,
    carbs: 5,
    fat: 2,
    fiber: 0,
    sugar: 3,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Süt", "Kefir Mayası"],
    healthBenefits: ["Probiyotik", "Kalsiyum"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_bev_008",
    name: "Salep",
    category: "İçecekler",
    subcategory: "Sıcak İçecekler",
    description: "Salep unu ile yapılan sıcak içecek",
    calories: 100,
    protein: 2,
    carbs: 20,
    fat: 2,
    fiber: 0,
    sugar: 15,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Salep Unu", "Süt", "Şeker", "Tarçın"],
    healthBenefits: ["Enerji"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_bev_009",
    name: "Boza",
    category: "İçecekler",
    subcategory: "Geleneksel İçecekler",
    description: "Tahıl ile yapılan geleneksel içecek",
    calories: 80,
    protein: 2,
    carbs: 18,
    fat: 0,
    fiber: 1,
    sugar: 10,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Tahıl", "Su", "Şeker"],
    healthBenefits: ["Enerji", "Lif"],
    warnings: ["Yüksek şeker", "Gluten içerebilir"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_bev_010",
    name: "Şıra",
    category: "İçecekler",
    subcategory: "Mevsimsel İçecekler",
    description: "Üzümden yapılan geleneksel içecek",
    calories: 80,
    protein: 0,
    carbs: 20,
    fat: 0,
    fiber: 0,
    sugar: 18,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Üzüm", "Su"],
    healthBenefits: ["Antioksidan"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== PILAVLAR =====
export const RICE_DISHES: TurkishFood[] = [
  {
    id: "tr_rice_001",
    name: "Beyaz Pilav",
    category: "Pilavlar",
    subcategory: "Basit Pilavlar",
    description: "Tereyağında pişmiş beyaz pirinç",
    calories: 200,
    protein: 4,
    carbs: 40,
    fat: 3,
    fiber: 1,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Pirinç", "Tereyağı", "Su", "Tuz"],
    healthBenefits: ["Enerji kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "tr_rice_002",
    name: "Şehriyeli Pilav",
    category: "Pilavlar",
    subcategory: "Basit Pilavlar",
    description: "Şehriye ve pirinçle yapılan pilav",
    calories: 220,
    protein: 5,
    carbs: 42,
    fat: 4,
    fiber: 1,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Pirinç", "Şehriye", "Tereyağı", "Su"],
    healthBenefits: ["Enerji kaynağı"],
    warnings: ["Gluten içerebilir"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "tr_rice_003",
    name: "Bulgur Pilav",
    category: "Pilavlar",
    subcategory: "Bulgurlu Pilavlar",
    description: "Bulgur ile yapılan pilav",
    calories: 180,
    protein: 6,
    carbs: 36,
    fat: 2,
    fiber: 4,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Bulgur", "Soğan", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Protein"],
    warnings: ["Gluten içerir"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_rice_004",
    name: "Etli Pilav",
    category: "Pilavlar",
    subcategory: "Etli Pilavlar",
    description: "Kırmızı et ile yapılan pilav",
    calories: 280,
    protein: 18,
    carbs: 38,
    fat: 6,
    fiber: 1,
    sugar: 0,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Pirinç", "Kırmızı Et", "Soğan", "Tereyağı"],
    healthBenefits: ["Yüksek protein", "Demir"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
  },
  {
    id: "tr_rice_005",
    name: "Tavuklu Pilav",
    category: "Pilavlar",
    subcategory: "Etli Pilavlar",
    description: "Tavuk eti ile yapılan pilav",
    calories: 260,
    protein: 20,
    carbs: 38,
    fat: 4,
    fiber: 1,
    sugar: 0,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Pirinç", "Tavuk Eti", "Soğan", "Tereyağı"],
    healthBenefits: ["Yüksek protein", "Düşük yağ"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
  },
  {
    id: "tr_rice_006",
    name: "Sebzeli Pilav",
    category: "Pilavlar",
    subcategory: "Sebzeli Pilavlar",
    description: "Sebzeler ile yapılan pilav",
    calories: 180,
    protein: 5,
    carbs: 36,
    fat: 3,
    fiber: 3,
    sugar: 2,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Pirinç", "Sebzeler", "Soğan", "Tereyağı"],
    healthBenefits: ["Vitamin", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "tr_rice_007",
    name: "Nohutlu Pilav",
    category: "Pilavlar",
    subcategory: "Baklagilli Pilavlar",
    description: "Nohut ile yapılan pilav",
    calories: 220,
    protein: 8,
    carbs: 40,
    fat: 3,
    fiber: 4,
    sugar: 1,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Pirinç", "Nohut", "Soğan", "Tereyağı"],
    healthBenefits: ["Protein", "Lif"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "tr_rice_008",
    name: "Mercimekli Pilav",
    category: "Pilavlar",
    subcategory: "Baklagilli Pilavlar",
    description: "Mercimek ile yapılan pilav",
    calories: 210,
    protein: 9,
    carbs: 38,
    fat: 3,
    fiber: 5,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Pirinç", "Mercimek", "Soğan", "Tereyağı"],
    healthBenefits: ["Protein", "Lif", "Demir"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "tr_rice_009",
    name: "Üzümlü Pilav",
    category: "Pilavlar",
    subcategory: "Tatlı Pilavlar",
    description: "Üzüm ile yapılan tatlı pilav",
    calories: 240,
    protein: 4,
    carbs: 48,
    fat: 3,
    fiber: 2,
    sugar: 12,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Pirinç", "Üzüm", "Tereyağı", "Şeker"],
    healthBenefits: ["Enerji", "Antioksidan"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: "tr_rice_010",
    name: "Fındıklı Pilav",
    category: "Pilavlar",
    subcategory: "Tatlı Pilavlar",
    description: "Fındık ile yapılan tatlı pilav",
    calories: 280,
    protein: 6,
    carbs: 42,
    fat: 10,
    fiber: 3,
    sugar: 8,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Pirinç", "Fındık", "Tereyağı", "Şeker"],
    healthBenefits: ["Sağlıklı yağlar", "Protein"],
    warnings: ["Yüksek yağ ve şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: false,
  },
];

// ===== KURUYEMIŞLER =====
export const NUTS_DRIED_FRUITS: TurkishFood[] = [
  {
    id: "tr_nuts_001",
    name: "Fındık",
    category: "Kuruyemişler",
    subcategory: "Fındık",
    description: "Türk fındığı",
    calories: 630,
    protein: 15,
    carbs: 17,
    fat: 61,
    fiber: 10,
    sugar: 4,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Fındık"],
    healthBenefits: ["Sağlıklı yağlar", "Vitamin E"],
    warnings: ["Yüksek kalori"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_002",
    name: "Ceviz",
    category: "Kuruyemişler",
    subcategory: "Ceviz",
    description: "Ceviz çekirdeği",
    calories: 650,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 7,
    sugar: 2,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Ceviz"],
    healthBenefits: ["Omega-3", "Sağlıklı yağlar"],
    warnings: ["Yüksek kalori"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_003",
    name: "Antep Fıstığı",
    category: "Kuruyemişler",
    subcategory: "Fıstık",
    description: "Antep fıstığı",
    calories: 570,
    protein: 20,
    carbs: 28,
    fat: 45,
    fiber: 10,
    sugar: 5,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Antep Fıstığı"],
    healthBenefits: ["Yüksek protein", "Sağlıklı yağlar"],
    warnings: ["Yüksek kalori"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_004",
    name: "Kaju",
    category: "Kuruyemişler",
    subcategory: "Fıstık",
    description: "Kaju fıstığı",
    calories: 550,
    protein: 18,
    carbs: 30,
    fat: 44,
    fiber: 3,
    sugar: 5,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Kaju"],
    healthBenefits: ["Mineral", "Sağlıklı yağlar"],
    warnings: ["Yüksek kalori"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_005",
    name: "Badem",
    category: "Kuruyemişler",
    subcategory: "Badem",
    description: "Badem çekirdeği",
    calories: 580,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    sugar: 4,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Badem"],
    healthBenefits: ["Yüksek protein", "Lif kaynağı"],
    warnings: ["Yüksek kalori"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_006",
    name: "Kuru Üzüm",
    category: "Kuruyemişler",
    subcategory: "Kuru Meyve",
    description: "Kurutulmuş üzüm",
    calories: 300,
    protein: 3,
    carbs: 79,
    fat: 0,
    fiber: 2,
    sugar: 59,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Üzüm"],
    healthBenefits: ["Enerji", "Antioksidan"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_007",
    name: "Kuru İncir",
    category: "Kuruyemişler",
    subcategory: "Kuru Meyve",
    description: "Kurutulmuş incir",
    calories: 250,
    protein: 3,
    carbs: 64,
    fat: 1,
    fiber: 1,
    sugar: 48,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["İncir"],
    healthBenefits: ["Lif kaynağı", "Kalsiyum"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_008",
    name: "Kuru Kayısı",
    category: "Kuruyemişler",
    subcategory: "Kuru Meyve",
    description: "Kurutulmuş kayısı",
    calories: 240,
    protein: 3,
    carbs: 62,
    fat: 0,
    fiber: 3,
    sugar: 53,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Kayısı"],
    healthBenefits: ["Demir", "Antioksidan"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_009",
    name: "Fıstık Ezmesi",
    category: "Kuruyemişler",
    subcategory: "Fıstık Ürünleri",
    description: "Fıstıktan yapılan sos",
    calories: 590,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    sugar: 3,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Fıstık"],
    healthBenefits: ["Protein", "Sağlıklı yağlar"],
    warnings: ["Yüksek kalori"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_nuts_010",
    name: "Badem Ezmesi",
    category: "Kuruyemişler",
    subcategory: "Fıstık Ürünleri",
    description: "Badem çekirdeğinden yapılan sos",
    calories: 580,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    sugar: 4,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Badem"],
    healthBenefits: ["Yüksek protein", "Lif kaynağı"],
    warnings: ["Yüksek kalori"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== MEYVELER =====
export const FRUITS: TurkishFood[] = [
  {
    id: "tr_fruit_001",
    name: "Elma",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze elma",
    calories: 52,
    protein: 0,
    carbs: 14,
    fat: 0,
    fiber: 2,
    sugar: 10,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Elma"],
    healthBenefits: ["Lif kaynağı", "Vitamin C"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_002",
    name: "Portakal",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze portakal",
    calories: 47,
    protein: 1,
    carbs: 12,
    fat: 0,
    fiber: 2,
    sugar: 9,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Portakal"],
    healthBenefits: ["Vitamin C", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_003",
    name: "Muz",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze muz",
    calories: 89,
    protein: 1,
    carbs: 23,
    fat: 0,
    fiber: 3,
    sugar: 12,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Muz"],
    healthBenefits: ["Potasyum", "Enerji"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_004",
    name: "Çilek",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze çilek",
    calories: 32,
    protein: 1,
    carbs: 8,
    fat: 0,
    fiber: 2,
    sugar: 5,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Çilek"],
    healthBenefits: ["Vitamin C", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_005",
    name: "Üzüm",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze üzüm",
    calories: 67,
    protein: 1,
    carbs: 17,
    fat: 0,
    fiber: 1,
    sugar: 16,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Üzüm"],
    healthBenefits: ["Antioksidan", "Resveratrol"],
    warnings: ["Yüksek şeker"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_006",
    name: "Karpuz",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze karpuz",
    calories: 30,
    protein: 1,
    carbs: 8,
    fat: 0,
    fiber: 0,
    sugar: 6,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Karpuz"],
    healthBenefits: ["Hidratasyon", "Vitamin C"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_007",
    name: "Melon",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze melon",
    calories: 34,
    protein: 1,
    carbs: 8,
    fat: 0,
    fiber: 1,
    sugar: 7,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Melon"],
    healthBenefits: ["Hidratasyon", "Vitamin A"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_008",
    name: "Nar",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze nar",
    calories: 68,
    protein: 1,
    carbs: 17,
    fat: 0,
    fiber: 4,
    sugar: 13,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Nar"],
    healthBenefits: ["Antioksidan", "Kalp sağlığı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_009",
    name: "Şeftali",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze şeftali",
    calories: 39,
    protein: 1,
    carbs: 10,
    fat: 0,
    fiber: 1,
    sugar: 8,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Şeftali"],
    healthBenefits: ["Vitamin A", "Vitamin C"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_fruit_010",
    name: "Vişne",
    category: "Meyveler",
    subcategory: "Mevsimsel Meyveler",
    description: "Taze vişne",
    calories: 63,
    protein: 1,
    carbs: 16,
    fat: 0,
    fiber: 2,
    sugar: 13,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Vişne"],
    healthBenefits: ["Antioksidan", "Uyku kalitesi"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== HAZIR GIDALAR =====
export const PROCESSED_FOODS: TurkishFood[] = [
  {
    id: "tr_proc_001",
    name: "Beyaz Ekmek",
    category: "Hazır Gıdalar",
    subcategory: "Ekmekler",
    description: "Beyaz un ile yapılan ekmek",
    calories: 265,
    protein: 8,
    carbs: 50,
    fat: 3,
    fiber: 2,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Beyaz Un", "Su", "Tuz", "Maya"],
    healthBenefits: ["Enerji kaynağı"],
    warnings: ["Gluten içerir", "Rafine karbohidrat"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_proc_002",
    name: "Tam Buğday Ekmeği",
    category: "Hazır Gıdalar",
    subcategory: "Ekmekler",
    description: "Tam buğday unu ile yapılan ekmek",
    calories: 250,
    protein: 9,
    carbs: 48,
    fat: 2,
    fiber: 7,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Tam Buğday Unu", "Su", "Tuz", "Maya"],
    healthBenefits: ["Lif kaynağı", "Vitamin B"],
    warnings: ["Gluten içerir"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_proc_003",
    name: "Simit",
    category: "Hazır Gıdalar",
    subcategory: "Ekmekler",
    description: "Sesam ile kaplı halka ekmek",
    calories: 280,
    protein: 9,
    carbs: 52,
    fat: 4,
    fiber: 2,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Sesam", "Tuz", "Maya"],
    healthBenefits: ["Enerji kaynağı", "Kalsiyum"],
    warnings: ["Gluten içerir"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_proc_004",
    name: "Beyaz Peynir",
    category: "Hazır Gıdalar",
    subcategory: "Süt Ürünleri",
    description: "Beyaz peynir",
    calories: 250,
    protein: 20,
    carbs: 1,
    fat: 20,
    fiber: 0,
    sugar: 0,
    servingSize: 50,
    servingUnit: "g",
    ingredients: ["Süt", "Rennet", "Tuz"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ ve sodyum"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_proc_005",
    name: "Yoğurt",
    category: "Hazır Gıdalar",
    subcategory: "Süt Ürünleri",
    description: "Fermente süt ürünü",
    calories: 60,
    protein: 3,
    carbs: 5,
    fat: 3,
    fiber: 0,
    sugar: 4,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Süt", "Yoğurt Mayası"],
    healthBenefits: ["Probiyotik", "Kalsiyum"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_proc_006",
    name: "Süt",
    category: "Hazır Gıdalar",
    subcategory: "Süt Ürünleri",
    description: "Taze inek sütü",
    calories: 61,
    protein: 3,
    carbs: 5,
    fat: 3,
    fiber: 0,
    sugar: 5,
    servingSize: 200,
    servingUnit: "ml",
    ingredients: ["Inek Sütü"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_proc_007",
    name: "Konserve Domates",
    category: "Hazır Gıdalar",
    subcategory: "Konserve Ürünleri",
    description: "Konserve domates",
    calories: 18,
    protein: 1,
    carbs: 4,
    fat: 0,
    fiber: 1,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Domates", "Tuz"],
    healthBenefits: ["Likopin", "Vitamin C"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_proc_008",
    name: "Konserve Balık",
    category: "Hazır Gıdalar",
    subcategory: "Konserve Ürünleri",
    description: "Konserve balık",
    calories: 200,
    protein: 25,
    carbs: 0,
    fat: 11,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Balık", "Yağ", "Tuz"],
    healthBenefits: ["Omega-3", "Protein"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_proc_009",
    name: "Konserve Nohut",
    category: "Hazır Gıdalar",
    subcategory: "Konserve Ürünleri",
    description: "Konserve nohut",
    calories: 120,
    protein: 7,
    carbs: 20,
    fat: 2,
    fiber: 5,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Nohut", "Tuz", "Su"],
    healthBenefits: ["Protein", "Lif"],
    warnings: ["Yüksek sodyum"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_proc_010",
    name: "Tereyağı",
    category: "Hazır Gıdalar",
    subcategory: "Yağlar",
    description: "Tereyağı",
    calories: 717,
    protein: 1,
    carbs: 0,
    fat: 81,
    fiber: 0,
    sugar: 0,
    servingSize: 10,
    servingUnit: "g",
    ingredients: ["Süt"],
    healthBenefits: ["Vitamin A", "Vitamin D"],
    warnings: ["Yüksek kalori ve yağ"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
];

// ===== TATLILAR =====
export const DESSERTS: TurkishFood[] = [
  {
    id: "tr_dessert_001",
    name: "Baklava",
    category: "Tatlılar",
    subcategory: "Filo Tatlıları",
    description: "Filo hamuru ve fındıkla yapılan tatlı",
    calories: 350,
    protein: 5,
    carbs: 45,
    fat: 18,
    fiber: 2,
    sugar: 35,
    servingSize: 50,
    servingUnit: "g",
    ingredients: ["Filo Hamuru", "Fındık", "Şeker", "Tereyağı"],
    healthBenefits: [],
    warnings: ["Yüksek şeker ve kalori"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_dessert_002",
    name: "Künefe",
    category: "Tatlılar",
    subcategory: "Peynir Tatlıları",
    description: "Kadayıf ve peynir ile yapılan tatlı",
    calories: 380,
    protein: 8,
    carbs: 48,
    fat: 18,
    fiber: 1,
    sugar: 38,
    servingSize: 50,
    servingUnit: "g",
    ingredients: ["Kadayıf", "Beyaz Peynir", "Şeker", "Tereyağı"],
    healthBenefits: [],
    warnings: ["Yüksek şeker ve kalori"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_dessert_003",
    name: "Şerbetli Tatlı",
    category: "Tatlılar",
    subcategory: "Şerbetli Tatlılar",
    description: "Şerbette bekletilmiş tatlı",
    calories: 320,
    protein: 3,
    carbs: 60,
    fat: 8,
    fiber: 1,
    sugar: 50,
    servingSize: 50,
    servingUnit: "g",
    ingredients: ["Un", "Şeker", "Tereyağı", "Su"],
    healthBenefits: [],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_dessert_004",
    name: "Lokum",
    category: "Tatlılar",
    subcategory: "Şekeri Tatlılar",
    description: "Geleneksel Türk lokumu",
    calories: 300,
    protein: 2,
    carbs: 75,
    fat: 0,
    fiber: 0,
    sugar: 70,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Şeker", "Un", "Nişasta", "Su"],
    healthBenefits: [],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_dessert_005",
    name: "Halva",
    category: "Tatlılar",
    subcategory: "Tahini Tatlıları",
    description: "Tahini ve şeker ile yapılan tatlı",
    calories: 520,
    protein: 15,
    carbs: 50,
    fat: 30,
    fiber: 5,
    sugar: 40,
    servingSize: 30,
    servingUnit: "g",
    ingredients: ["Tahini", "Şeker", "Fındık"],
    healthBenefits: ["Protein", "Sağlıklı yağlar"],
    warnings: ["Yüksek kalori ve şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_dessert_006",
    name: "Sütlaç",
    category: "Tatlılar",
    subcategory: "Sütlü Tatlılar",
    description: "Fırında pişmiş sütlaç",
    calories: 150,
    protein: 4,
    carbs: 28,
    fat: 2,
    fiber: 0,
    sugar: 22,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Pirinç", "Süt", "Şeker", "Vanilya"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_dessert_007",
    name: "Muhallebi",
    category: "Tatlılar",
    subcategory: "Sütlü Tatlılar",
    description: "Nişasta ve süt ile yapılan tatlı",
    calories: 140,
    protein: 3,
    carbs: 26,
    fat: 2,
    fiber: 0,
    sugar: 20,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Nişasta", "Süt", "Şeker", "Vanilya"],
    healthBenefits: ["Kalsiyum"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_dessert_008",
    name: "Dondurma",
    category: "Tatlılar",
    subcategory: "Soğuk Tatlılar",
    description: "Türk dondurması",
    calories: 200,
    protein: 4,
    carbs: 28,
    fat: 8,
    fiber: 0,
    sugar: 24,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Süt", "Şeker", "Yumurta", "Salep"],
    healthBenefits: ["Kalsiyum"],
    warnings: ["Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: true,
    isVegetarian: true,
  },
  {
    id: "tr_dessert_009",
    name: "Pasta",
    category: "Tatlılar",
    subcategory: "Pastalar",
    description: "Pasta",
    calories: 280,
    protein: 3,
    carbs: 40,
    fat: 12,
    fiber: 1,
    sugar: 30,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Şeker", "Yumurta", "Tereyağı"],
    healthBenefits: [],
    warnings: ["Yüksek şeker ve kalori"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_dessert_010",
    name: "Bisküvi",
    category: "Tatlılar",
    subcategory: "Bisküviler",
    description: "Bisküvi",
    calories: 420,
    protein: 8,
    carbs: 60,
    fat: 16,
    fiber: 2,
    sugar: 25,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Şeker", "Yumurta", "Tereyağı"],
    healthBenefits: [],
    warnings: ["Yüksek kalori"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
];

// ===== ETLİ YEMEKLER =====
export const MEAT_DISHES: TurkishFood[] = [
  {
    id: "tr_meat_001",
    name: "Adana Kebap",
    category: "Etli Yemekler",
    subcategory: "Kebaplar",
    description: "Baharat ve ince kıyıma sarılmış kebap",
    calories: 380,
    protein: 35,
    carbs: 2,
    fat: 28,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Kıyma", "Baharat", "Soğan", "Maydanoz"],
    healthBenefits: ["Yüksek protein", "Demir kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_meat_002",
    name: "Şiş Kebap",
    category: "Etli Yemekler",
    subcategory: "Kebaplar",
    description: "Kübik et parçaları ile yapılan kebap",
    calories: 350,
    protein: 38,
    carbs: 1,
    fat: 20,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Et", "Soğan", "Biber", "Domates"],
    healthBenefits: ["Yüksek protein", "Demir"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_meat_003",
    name: "Döner Kebap",
    category: "Etli Yemekler",
    subcategory: "Kebaplar",
    description: "Dönerci tarafından hazırlanan döner kebap",
    calories: 420,
    protein: 32,
    carbs: 3,
    fat: 32,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Et", "Baharat", "Soğan"],
    healthBenefits: ["Yüksek protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_meat_004",
    name: "Köfte",
    category: "Etli Yemekler",
    subcategory: "Köfteler",
    description: "Geleneksel Türk köftesi",
    calories: 280,
    protein: 28,
    carbs: 8,
    fat: 14,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Kıyma", "Ekmek", "Yumurta", "Baharat"],
    healthBenefits: ["Yüksek protein"],
    warnings: ["Gluten içerebilir"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
  },
  {
    id: "tr_meat_005",
    name: "İçli Köfte",
    category: "Etli Yemekler",
    subcategory: "Köfteler",
    description: "Bulgur ve kıyma ile yapılan köfte",
    calories: 320,
    protein: 18,
    carbs: 28,
    fat: 16,
    fiber: 2,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Bulgur", "Kıyma", "Soğan", "Baharat"],
    healthBenefits: ["Protein", "Lif"],
    warnings: ["Gluten içerir"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
  },
  {
    id: "tr_meat_006",
    name: "Tavuk Şiş",
    category: "Etli Yemekler",
    subcategory: "Tavuk Yemekleri",
    description: "Tavuk göğsü ile yapılan şiş",
    calories: 280,
    protein: 38,
    carbs: 1,
    fat: 13,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Tavuk Göğsü", "Soğan", "Biber"],
    healthBenefits: ["Yüksek protein", "Düşük yağ"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_meat_007",
    name: "Tavuk Döner",
    category: "Etli Yemekler",
    subcategory: "Tavuk Yemekleri",
    description: "Tavuk döner",
    calories: 320,
    protein: 35,
    carbs: 2,
    fat: 18,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Tavuk", "Baharat", "Soğan"],
    healthBenefits: ["Yüksek protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_meat_008",
    name: "Kuru Fasulye ve Eti",
    category: "Etli Yemekler",
    subcategory: "Güveç Yemekleri",
    description: "Kuru fasulye ve et ile yapılan güveç",
    calories: 240,
    protein: 22,
    carbs: 22,
    fat: 8,
    fiber: 5,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Kuru Fasulye", "Et", "Soğan", "Domates"],
    healthBenefits: ["Protein", "Lif", "Demir"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_meat_009",
    name: "Nohut ve Eti",
    category: "Etli Yemekler",
    subcategory: "Güveç Yemekleri",
    description: "Nohut ve et ile yapılan güveç",
    calories: 260,
    protein: 24,
    carbs: 20,
    fat: 10,
    fiber: 4,
    sugar: 1,
    servingSize: 200,
    servingUnit: "g",
    ingredients: ["Nohut", "Et", "Soğan", "Domates"],
    healthBenefits: ["Protein", "Lif", "Mineral"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_meat_010",
    name: "Kıymalı Pide",
    category: "Etli Yemekler",
    subcategory: "Pideler",
    description: "Kıyma dolgulu pide",
    calories: 320,
    protein: 14,
    carbs: 36,
    fat: 14,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Kıyma", "Soğan", "Domates"],
    healthBenefits: ["Protein", "Enerji"],
    warnings: ["Gluten içerir"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
  },
];

// ===== IZZARA YEMEKLER =====
export const GRILLED_FOODS: TurkishFood[] = [
  {
    id: "tr_grill_001",
    name: "Izgara Tavuk",
    category: "Izzara Yemekler",
    subcategory: "Tavuk",
    description: "Izzarada pişmiş tavuk",
    calories: 280,
    protein: 38,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Tavuk Göğsü", "Baharat", "Limon"],
    healthBenefits: ["Yüksek protein", "Düşük yağ"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_grill_002",
    name: "Izgara Balık",
    category: "Izzara Yemekler",
    subcategory: "Balık",
    description: "Izzarada pişmiş balık",
    calories: 240,
    protein: 35,
    carbs: 0,
    fat: 11,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Balık", "Limon", "Baharat"],
    healthBenefits: ["Omega-3", "Yüksek protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_grill_003",
    name: "Izgara Patlıcan",
    category: "Izzara Yemekler",
    subcategory: "Sebze",
    description: "Izzarada pişmiş patlıcan",
    calories: 80,
    protein: 2,
    carbs: 12,
    fat: 4,
    fiber: 3,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Zeytin Yağı", "Baharat"],
    healthBenefits: ["Lif", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_grill_004",
    name: "Izgara Biber",
    category: "Izzara Yemekler",
    subcategory: "Sebze",
    description: "Izzarada pişmiş biber",
    calories: 40,
    protein: 1,
    carbs: 8,
    fat: 1,
    fiber: 2,
    sugar: 3,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Biber", "Zeytin Yağı"],
    healthBenefits: ["Vitamin C", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_grill_005",
    name: "Izgara Domates",
    category: "Izzara Yemekler",
    subcategory: "Sebze",
    description: "Izzarada pişmiş domates",
    calories: 35,
    protein: 1,
    carbs: 7,
    fat: 1,
    fiber: 1,
    sugar: 4,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Domates", "Zeytin Yağı", "Baharat"],
    healthBenefits: ["Likopin", "Vitamin C"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_grill_006",
    name: "Izgara Karides",
    category: "Izzara Yemekler",
    subcategory: "Deniz Ürünleri",
    description: "Izzarada pişmiş karides",
    calories: 100,
    protein: 20,
    carbs: 0,
    fat: 2,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Karides", "Limon", "Baharat"],
    healthBenefits: ["Yüksek protein", "Düşük yağ"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_grill_007",
    name: "Izgara Midye",
    category: "Izzara Yemekler",
    subcategory: "Deniz Ürünleri",
    description: "Izzarada pişmiş midye",
    calories: 80,
    protein: 12,
    carbs: 3,
    fat: 2,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Midye", "Limon", "Baharat"],
    healthBenefits: ["Yüksek protein", "Demir"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_grill_008",
    name: "Izgara Kırmızı Et",
    category: "Izzara Yemekler",
    subcategory: "Et",
    description: "Izzarada pişmiş kırmızı et",
    calories: 320,
    protein: 38,
    carbs: 0,
    fat: 18,
    fiber: 0,
    sugar: 0,
    servingSize: 150,
    servingUnit: "g",
    ingredients: ["Kırmızı Et", "Baharat", "Limon"],
    healthBenefits: ["Yüksek protein", "Demir"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_grill_009",
    name: "Izgara Köfte",
    category: "Izzara Yemekler",
    subcategory: "Köfteler",
    description: "Izzarada pişmiş köfte",
    calories: 280,
    protein: 28,
    carbs: 8,
    fat: 14,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Kıyma", "Ekmek", "Yumurta", "Baharat"],
    healthBenefits: ["Yüksek protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
  },
  {
    id: "tr_grill_010",
    name: "Izgara Halloumi",
    category: "Izzara Yemekler",
    subcategory: "Peynir",
    description: "Izzarada pişmiş halloumi peyniri",
    calories: 280,
    protein: 22,
    carbs: 1,
    fat: 22,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Halloumi Peyniri", "Zeytin Yağı"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Yüksek yağ"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
  },
];

// ===== SAKADATLI YEMEKLER =====
export const OFFAL_DISHES: TurkishFood[] = [
  {
    id: "tr_offal_001",
    name: "Işkembe Çorbası",
    category: "Sakadatli Yemekler",
    subcategory: "Çorbalar",
    description: "Işkembe ile yapılan çorba",
    calories: 140,
    protein: 18,
    carbs: 6,
    fat: 5,
    fiber: 0,
    sugar: 0,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Işkembe", "Sarımsak", "Limon", "Un"],
    healthBenefits: ["Yüksek protein", "Kolajen"],
    warnings: ["Yüksek kolesterol"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: false,
  },
  {
    id: "tr_offal_002",
    name: "Ciğer Kebap",
    category: "Sakadatli Yemekler",
    subcategory: "Kebaplar",
    description: "Ciğer ile yapılan kebap",
    calories: 280,
    protein: 32,
    carbs: 2,
    fat: 15,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Ciğer", "Baharat", "Soğan"],
    healthBenefits: ["Yüksek protein", "Demir", "Vitamin A"],
    warnings: ["Yüksek kolesterol"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_offal_003",
    name: "Böbrek",
    category: "Sakadatli Yemekler",
    subcategory: "Etler",
    description: "Böbrek eti",
    calories: 120,
    protein: 20,
    carbs: 0,
    fat: 4,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Böbrek", "Baharat"],
    healthBenefits: ["Yüksek protein", "Demir"],
    warnings: ["Yüksek kolesterol"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_offal_004",
    name: "Kelle Paça",
    category: "Sakadatli Yemekler",
    subcategory: "Çorbalar",
    description: "Kelle ve paça ile yapılan çorba",
    calories: 160,
    protein: 22,
    carbs: 4,
    fat: 6,
    fiber: 0,
    sugar: 0,
    servingSize: 250,
    servingUnit: "ml",
    ingredients: ["Kelle", "Paça", "Soğan", "Limon"],
    healthBenefits: ["Yüksek protein", "Kolajen"],
    warnings: ["Yüksek kolesterol"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_offal_005",
    name: "Beyin Kebap",
    category: "Sakadatli Yemekler",
    subcategory: "Kebaplar",
    description: "Beyin ile yapılan kebap",
    calories: 200,
    protein: 18,
    carbs: 2,
    fat: 14,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Beyin", "Baharat", "Soğan"],
    healthBenefits: ["Yüksek protein", "Kolajen"],
    warnings: ["Yüksek kolesterol"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_offal_006",
    name: "Ciğer Tava",
    category: "Sakadatli Yemekler",
    subcategory: "Tavalar",
    description: "Ciğer tava",
    calories: 320,
    protein: 32,
    carbs: 6,
    fat: 18,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Ciğer", "Soğan", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Yüksek protein", "Demir"],
    warnings: ["Yüksek kolesterol"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_offal_007",
    name: "Yürek",
    category: "Sakadatli Yemekler",
    subcategory: "Etler",
    description: "Yürek eti",
    calories: 110,
    protein: 19,
    carbs: 0,
    fat: 3,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Yürek", "Baharat"],
    healthBenefits: ["Yüksek protein", "Demir"],
    warnings: ["Yüksek kolesterol"],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_offal_008",
    name: "Akciğer",
    category: "Sakadatli Yemekler",
    subcategory: "Etler",
    description: "Akciğer eti",
    calories: 100,
    protein: 18,
    carbs: 0,
    fat: 2,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Akciğer", "Baharat"],
    healthBenefits: ["Yüksek protein", "Demir"],
    warnings: [],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_offal_009",
    name: "Tırnak",
    category: "Sakadatli Yemekler",
    subcategory: "Etler",
    description: "Tırnak eti",
    calories: 130,
    protein: 20,
    carbs: 0,
    fat: 5,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Tırnak", "Baharat"],
    healthBenefits: ["Yüksek protein", "Kolajen"],
    warnings: [],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
  {
    id: "tr_offal_010",
    name: "Saçak",
    category: "Sakadatli Yemekler",
    subcategory: "Etler",
    description: "Saçak eti",
    calories: 140,
    protein: 22,
    carbs: 0,
    fat: 5,
    fiber: 0,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Saçak", "Baharat"],
    healthBenefits: ["Yüksek protein", "Kolajen"],
    warnings: [],
    isRecommended: false,
    isDiabeticFriendly: true,
    isGlutenFree: true,
  },
];

// ===== HAMUR İŞLERİ =====
export const PASTRIES: TurkishFood[] = [
  {
    id: "tr_pastry_001",
    name: "Pide",
    category: "Hamur İşleri",
    subcategory: "Pideler",
    description: "Peynir ve et dolgulu pide",
    calories: 280,
    protein: 12,
    carbs: 35,
    fat: 12,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Peynir", "Kıyma", "Yumurta"],
    healthBenefits: ["Enerji kaynağı"],
    warnings: ["Gluten içerir"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: false,
  },
  {
    id: "tr_pastry_002",
    name: "Börek",
    category: "Hamur İşleri",
    subcategory: "Börekleri",
    description: "Peynir dolgulu börek",
    calories: 300,
    protein: 10,
    carbs: 32,
    fat: 15,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Filo Hamuru", "Peynir", "Yumurta", "Tereyağı"],
    healthBenefits: ["Kalsiyum", "Protein"],
    warnings: ["Gluten içerir", "Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_pastry_003",
    name: "Sigara Böreği",
    category: "Hamur İşleri",
    subcategory: "Börekleri",
    description: "Peynir dolgulu sigara şeklinde börek",
    calories: 320,
    protein: 8,
    carbs: 28,
    fat: 20,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Filo Hamuru", "Peynir", "Tereyağı"],
    healthBenefits: ["Kalsiyum"],
    warnings: ["Gluten içerir", "Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_pastry_004",
    name: "Gül Böreği",
    category: "Hamur İşleri",
    subcategory: "Börekleri",
    description: "Peynir dolgulu gül şeklinde börek",
    calories: 310,
    protein: 9,
    carbs: 30,
    fat: 17,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Filo Hamuru", "Peynir", "Tereyağı"],
    healthBenefits: ["Kalsiyum"],
    warnings: ["Gluten içerir", "Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_pastry_005",
    name: "Tatlı Börek",
    category: "Hamur İşleri",
    subcategory: "Tatlı Börekleri",
    description: "Ceviz ve şeker dolgulu börek",
    calories: 350,
    protein: 6,
    carbs: 45,
    fat: 16,
    fiber: 1,
    sugar: 30,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Filo Hamuru", "Ceviz", "Şeker", "Tereyağı"],
    healthBenefits: ["Sağlıklı yağlar"],
    warnings: ["Gluten içerir", "Yüksek şeker"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_pastry_006",
    name: "Manti",
    category: "Hamur İşleri",
    subcategory: "Mantılar",
    description: "Kıyma dolgulu manti",
    calories: 260,
    protein: 14,
    carbs: 32,
    fat: 8,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Kıyma", "Soğan", "Yoğurt"],
    healthBenefits: ["Protein", "Enerji"],
    warnings: ["Gluten içerir"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
  },
  {
    id: "tr_pastry_007",
    name: "Gözleme",
    category: "Hamur İşleri",
    subcategory: "Gözlemeler",
    description: "Peynir ve ot dolgulu gözleme",
    calories: 240,
    protein: 8,
    carbs: 30,
    fat: 10,
    fiber: 2,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Peynir", "Otlar", "Zeytin Yağı"],
    healthBenefits: ["Kalsiyum", "Lif"],
    warnings: ["Gluten içerir"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_pastry_008",
    name: "Lahmacun",
    category: "Hamur İşleri",
    subcategory: "Lahmacunlar",
    description: "Kıymalı lahmacun",
    calories: 280,
    protein: 12,
    carbs: 36,
    fat: 10,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Kıyma", "Domates", "Baharat"],
    healthBenefits: ["Protein", "Enerji"],
    warnings: ["Gluten içerir"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
  },
  {
    id: "tr_pastry_009",
    name: "Çörek",
    category: "Hamur İşleri",
    subcategory: "Çörekler",
    description: "Sesam ve peynir dolgulu çörek",
    calories: 290,
    protein: 9,
    carbs: 36,
    fat: 12,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Peynir", "Sesam", "Yumurta"],
    healthBenefits: ["Kalsiyum"],
    warnings: ["Gluten içerir"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
  {
    id: "tr_pastry_010",
    name: "Poğaça",
    category: "Hamur İşleri",
    subcategory: "Poğaçalar",
    description: "Peynir dolgulu poğaça",
    calories: 310,
    protein: 8,
    carbs: 34,
    fat: 16,
    fiber: 1,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Un", "Peynir", "Yumurta", "Tereyağı"],
    healthBenefits: ["Kalsiyum"],
    warnings: ["Gluten içerir", "Yüksek yağ"],
    isRecommended: false,
    isDiabeticFriendly: false,
    isGlutenFree: false,
    isVegetarian: true,
  },
];

// ===== ZEYTINYAĞLI YEMEKLER =====
export const OLIVE_OIL_DISHES: TurkishFood[] = [
  {
    id: "tr_olive_001",
    name: "Zeytinyağlı Yaprak Sarması",
    category: "Zeytinyağlı Yemekler",
    subcategory: "Sarmaları",
    description: "Asma yaprağına sarılmış pirinç ve otlar",
    calories: 180,
    protein: 4,
    carbs: 22,
    fat: 9,
    fiber: 3,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Asma Yaprağı", "Pirinç", "Zeytin Yağı", "Otlar"],
    healthBenefits: ["Lif kaynağı", "Sağlıklı yağlar"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_olive_002",
    name: "Zeytinyağlı Patlıcan",
    category: "Zeytinyağlı Yemekler",
    subcategory: "Sebze Yemekleri",
    description: "Patlıcan ve domates ile yapılan zeytinyağlı yemek",
    calories: 150,
    protein: 3,
    carbs: 16,
    fat: 8,
    fiber: 4,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Domates", "Zeytin Yağı", "Sarımsak"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_olive_003",
    name: "Zeytinyağlı Kabak",
    category: "Zeytinyağlı Yemekler",
    subcategory: "Sebze Yemekleri",
    description: "Kabak ve soğan ile yapılan zeytinyağlı yemek",
    calories: 120,
    protein: 2,
    carbs: 14,
    fat: 6,
    fiber: 3,
    sugar: 2,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Kabak", "Soğan", "Zeytin Yağı", "Dill"],
    healthBenefits: ["Düşük kalori", "Lif kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_olive_004",
    name: "Imam Bayıldı",
    category: "Zeytinyağlı Yemekler",
    subcategory: "Sebze Yemekleri",
    description: "Patlıcan içine soğan ve domates dolgulu yemek",
    calories: 160,
    protein: 3,
    carbs: 18,
    fat: 8,
    fiber: 4,
    sugar: 3,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Patlıcan", "Soğan", "Domates", "Zeytin Yağı"],
    healthBenefits: ["Lif kaynağı", "Antioksidan"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_olive_005",
    name: "Zeytinyağlı Fasulye",
    category: "Zeytinyağlı Yemekler",
    subcategory: "Baklagil Yemekleri",
    description: "Fasulye ve domates ile yapılan zeytinyağlı yemek",
    calories: 140,
    protein: 6,
    carbs: 20,
    fat: 4,
    fiber: 5,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Fasulye", "Domates", "Zeytin Yağı", "Soğan"],
    healthBenefits: ["Lif kaynağı", "Protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_olive_006",
    name: "Zeytinyağlı Mercimek",
    category: "Zeytinyağlı Yemekler",
    subcategory: "Baklagil Yemekleri",
    description: "Mercimek ve domates ile yapılan zeytinyağlı yemek",
    calories: 130,
    protein: 7,
    carbs: 18,
    fat: 4,
    fiber: 5,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Mercimek", "Domates", "Zeytin Yağı", "Soğan"],
    healthBenefits: ["Lif kaynağı", "Protein"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "tr_olive_007",
    name: "Zeytinyağlı Nohut",
    category: "Zeytinyağlı Yemekler",
    subcategory: "Baklagil Yemekleri",
    description: "Nohut ve domates ile yapılan zeytinyağlı yemek",
    calories: 150,
    protein: 7,
    carbs: 22,
    fat: 4,
    fiber: 6,
    sugar: 1,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Nohut", "Domates", "Zeytin Yağı", "Soğan"],
    healthBenefits: ["Protein", "Lif kaynağı"],
    warnings: [],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: true,
    isVegetarian: true,
    isVegan: true,
  },
];

// ===== KÖFTELER =====
export const MEATBALLS: TurkishFood[] = [
  {
    id: "tr_meatball_001",
    name: "Köfte",
    category: "Köfteler",
    subcategory: "Geleneksel Köfteler",
    description: "Geleneksel Türk köftesi",
    calories: 280,
    protein: 28,
    carbs: 8,
    fat: 14,
    fiber: 1,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Kıyma", "Ekmek", "Yumurta", "Baharat"],
    healthBenefits: ["Yüksek protein"],
    warnings: ["Gluten içerebilir"],
    isRecommended: true,
    isDiabeticFriendly: true,
    isGlutenFree: false,
  },
  {
    id: "tr_meatball_002",
    name: "İçli Köfte",
    category: "Köfteler",
    subcategory: "Bulgurlu Köfteler",
    description: "Bulgur ve kıyma ile yapılan köfte",
    calories: 320,
    protein: 18,
    carbs: 28,
    fat: 16,
    fiber: 2,
    sugar: 0,
    servingSize: 100,
    servingUnit: "g",
    ingredients: ["Bulgur", "Kıyma", "Soğan", "Baharat"],
    healthBenefits: ["Protein", "Lif"],
    warnings: ["Gluten içerir"],
    isRecommended: true,
    isDiabeticFriendly: false,
    isGlutenFree: false,
  },
];

// ===== ÖZELDİ DURUMLAR =====
export interface SpecialDiet {
  id: string;
  name: string;
  description: string;
  recommendations: string[];
  restrictions: string[];
  foods: TurkishFood[];
}

export const SPECIAL_DIETS: SpecialDiet[] = [
  {
    id: "special_diabetes",
    name: "Şeker Hastalığı (Diyabet)",
    description: "Kan şekerini kontrol altında tutmak için özel beslenme planı",
    recommendations: [
      "Düşük glisemik indeksli gıdalar tercih edin",
      "Lif açısından zengin gıdalar tüketin",
      "Karbohidratları kontrollü miktarda alın",
      "Şeker ve şekerli gıdalardan kaçının",
      "Tam tahılları tercih edin",
      "Protein ve sağlıklı yağları dengeli alın",
    ],
    restrictions: [
      "Şeker",
      "Şekerli içecekler",
      "Beyaz ekmek",
      "Beyaz pirinç",
      "Tatlılar",
      "Rafine karbohidratlar",
    ],
    foods: [
      SOUPS[0], // Mercimek Çorbası
      VEGETABLE_DISHES[8], // Nohut Yemeği
      SALADS[0], // Çoban Salatası
      FRUITS[0], // Elma
      NUTS_DRIED_FRUITS[0], // Fındık
    ],
  },
  {
    id: "special_gluten",
    name: "Gluten Hassasiyeti (Çölyak)",
    description: "Gluten içermeyen gıdalarla beslenme planı",
    recommendations: [
      "Gluten içermeyen ürünleri tercih edin",
      "Doğal gıdaları seçin",
      "Etiketleri dikkatle kontrol edin",
      "Çapraz kontaminasyondan kaçının",
      "Gluten içermeyen un ve tahılları kullanın",
    ],
    restrictions: [
      "Buğday",
      "Arpa",
      "Çavdar",
      "Hamur işleri",
      "Ekmek",
      "Pasta",
      "Bisküvi",
    ],
    foods: [
      SOUPS[0], // Mercimek Çorbası
      VEGETABLE_DISHES[0], // Zeytinyağlı Yaprak Sarması
      SALADS[0], // Çoban Salatası
      MEAT_DISHES[0], // Adana Kebap
      GRILLED_FOODS[0], // Izgara Tavuk
    ],
  },
  {
    id: "special_vegan",
    name: "Vegan Beslenme",
    description: "Hiçbir hayvan ürünü içermeyen beslenme planı",
    recommendations: [
      "Bitkisel protein kaynakları kullanın",
      "Çeşitli sebze ve meyve tüketin",
      "Tam tahılları tercih edin",
      "Kuruyemişleri düzenli tüketin",
      "Vitamin B12 takviyesi alın",
    ],
    restrictions: [
      "Et",
      "Tavuk",
      "Balık",
      "Süt",
      "Peynir",
      "Yoğurt",
      "Yumurta",
      "Tereyağı",
    ],
    foods: [
      SOUPS[0], // Mercimek Çorbası
      VEGETABLE_DISHES[8], // Nohut Yemeği
      SALADS[4], // Hummus
      FRUITS[0], // Elma
      NUTS_DRIED_FRUITS[0], // Fındık
    ],
  },
  {
    id: "special_vegetarian",
    name: "Vegetaryen Beslenme",
    description: "Et ve balık içermeyen beslenme planı",
    recommendations: [
      "Bitkisel protein kaynakları kullanın",
      "Baklagilleri düzenli tüketin",
      "Süt ürünlerini dengeli alın",
      "Yumurta tüketin",
      "Çeşitli sebze ve meyve seçin",
    ],
    restrictions: [
      "Kırmızı et",
      "Tavuk",
      "Balık",
      "Deniz ürünleri",
    ],
    foods: [
      SOUPS[0], // Mercimek Çorbası
      VEGETABLE_DISHES[8], // Nohut Yemeği
      SALADS[4], // Hummus
      PROCESSED_FOODS[4], // Yoğurt
      NUTS_DRIED_FRUITS[0], // Fındık
    ],
  },
  {
    id: "special_lactose",
    name: "Laktoz İntoleransı",
    description: "Laktoz içermeyen gıdalarla beslenme planı",
    recommendations: [
      "Laktoz içermeyen süt ürünleri kullanın",
      "Fermente süt ürünlerini tercih edin",
      "Bitkisel sütleri kullanın",
      "Etiketleri kontrol edin",
      "Kalsiyum takviyesi alın",
    ],
    restrictions: [
      "Süt",
      "Peynir",
      "Tereyağı",
      "Krema",
      "Laktoz içeren ürünler",
    ],
    foods: [
      SOUPS[0], // Mercimek Çorbası
      VEGETABLE_DISHES[8], // Nohut Yemeği
      SALADS[0], // Çoban Salatası
      MEAT_DISHES[0], // Adana Kebap
      FRUITS[0], // Elma
    ],
  },
  {
    id: "special_hypertension",
    name: "Yüksek Tansiyon (Hipertansiyon)",
    description: "Sodyum kısıtlı beslenme planı",
    recommendations: [
      "Tuz tüketimini azaltın",
      "Potasyum açısından zengin gıdalar tüketin",
      "Taze gıdaları tercih edin",
      "Konserve ürünlerden kaçının",
      "Sağlıklı yağları tercih edin",
    ],
    restrictions: [
      "Tuz",
      "İşlenmiş gıdalar",
      "Konserve ürünleri",
      "Yüksek sodyumlu ürünler",
      "Turşu",
    ],
    foods: [
      SOUPS[0], // Mercimek Çorbası
      VEGETABLE_DISHES[0], // Zeytinyağlı Yaprak Sarması
      SALADS[0], // Çoban Salatası
      FRUITS[0], // Elma
      NUTS_DRIED_FRUITS[0], // Fındık
    ],
  },
];

// ===== TÜM KATEGORILERI BIRLEŞTIR =====
export const ALL_TURKISH_FOODS: TurkishFood[] = [
  ...SOUPS,
  ...VEGETABLE_DISHES,
  ...SALADS,
  ...BEVERAGES,
  ...RICE_DISHES,
  ...NUTS_DRIED_FRUITS,
  ...FRUITS,
  ...PROCESSED_FOODS,
  ...DESSERTS,
  ...MEAT_DISHES,
  ...GRILLED_FOODS,
  ...OFFAL_DISHES,
  ...PASTRIES,
  ...OLIVE_OIL_DISHES,
  ...MEATBALLS,
];

// ===== İSTATİSTİKLER =====
export const STATISTICS = {
  totalFoods: ALL_TURKISH_FOODS.length,
  recommendedFoods: ALL_TURKISH_FOODS.filter(f => f.isRecommended).length,
  prohibitedFoods: ALL_TURKISH_FOODS.filter(f => f.isProhibited).length,
  diabeticFriendly: ALL_TURKISH_FOODS.filter(f => f.isDiabeticFriendly).length,
  glutenFree: ALL_TURKISH_FOODS.filter(f => f.isGlutenFree).length,
  vegetarian: ALL_TURKISH_FOODS.filter(f => f.isVegetarian).length,
  vegan: ALL_TURKISH_FOODS.filter(f => f.isVegan).length,
  specialDiets: SPECIAL_DIETS.length,
};
